- name: Svantaggio - Minore
  subclass: Analfabeta
  domains: ""
  description: "Il personaggio non sa leggere né scrivere in nessuna lingua. Sa scrivere il proprio nome e riconoscere una segnale di STOP, ma poco altro."
  source: core

- name: Svantaggio - Minore
  subclass: Anemico
  domains: ""
  description: "Il personaggio è particolarmente esposto alle malattie, alla fatica e agli effetti ambientali. Tutti i tiri di Vigore per resistere alla Fatica subiscono un modificatore di -2."
  source: core

- name: Svantaggio - Maggiore
  subclass: Anziano
  domains: ""
  description: "Il personaggio è avanti negli anni. Passo ridotto di 1, -1 al dado per correre (risultato minimo 1), -1 ai tiri di Agilità, Forza e Vigore (ma non alle abilità associate). In compenso, ottiene 5 punti abilità aggiuntivi da spendere in abilità collegate all'Intelligenza."
  source: core

- name: Svantaggio - Maggiore
  subclass: Arrogante
  domains: ""
  description: "Il personaggio è convinto di essere il migliore nel suo campo. Deve umiliare l'avversario e dimostrare la propria superiorità. In battaglia punta dritto al nemico più pericoloso, ignorando quelli meno pericolosi che si frappongono."
  source: core

- name: Svantaggio - Maggiore/Minore
  subclass: Avido
  domains: ""
  description: "Il personaggio misura il proprio valore sulla base delle ricchezze possedute. Minore: discute aspramente sulla divisione di tesori e ricompense. Maggiore: è pronto a litigare per qualsiasi cosa ritiene ingiusta, e potrebbe arrivare a uccidere per ottenerla."
  source: core

- name: Svantaggio - Maggiore/Minore
  subclass: Brutto
  domains: ""
  description: "Il personaggio non è attraente e subisce penalità ai tiri di Persuasione. Minore: -1 a Persuasione. Maggiore: -2 a Persuasione."
  source: core

- name: Svantaggio - Minore
  subclass: Cauto
  domains: ""
  description: "Il personaggio sente la necessità di pianificare le proprie azioni con cura e non prende mai decisioni d'impulso."
  source: core

- name: Svantaggio - Minore
  subclass: Chiacchierone
  domains: ""
  description: "Il personaggio non è bravo a mantenere un segreto. Svela i piani del gruppo e rivela informazioni riservate, di solito nel peggior momento possibile."
  source: core

- name: Svantaggio - Maggiore
  subclass: Cieco
  domains: ""
  description: "Il personaggio è completamente privo di vista. Tutte le azioni che richiedono la visione subiscono una penalità di -6. Per compensare, ottiene un Vantaggio gratuito a sua scelta."
  source: core

- name: Svantaggio - Maggiore
  subclass: Codice d'Onore
  domains: ""
  description: "Per il personaggio l'onore è molto importante. Mantiene sempre la parola data, rispetta i prigionieri e in generale tenta di agire sempre seguendo una linea di condotta corrispondente all'idea di gentiluomo o gentildonna tipica del suo mondo."
  source: core

- name: Svantaggio - Maggiore
  subclass: Curioso
  domains: ""
  description: "La curiosità uccide il gatto. I personaggi curiosi devono sempre mettere il naso dappertutto e vogliono sempre sapere cosa si nasconde dietro un potenziale mistero o segreto."
  source: core

- name: Svantaggio - Minore
  subclass: Desiderio di Morte
  domains: ""
  description: "Il personaggio tratta la propria vita come meno importante di un nobile e pericolosissimo obiettivo. Non getta via la vita senza ragione, ma se si presenta una possibilità di raggiungere il proprio scopo è pronto a correre qualsiasi rischio."
  source: core

- name: Svantaggio - Maggiore/Minore
  subclass: Dipendenza
  domains: ""
  description: "Il personaggio ha un'abitudine fastidiosa o rischiosa. Minore: irritante ma non pericolosa. Maggiore: dipendenza fisica o psicologica debilitante e potenzialmente letale (alcolismo, droghe, ecc.). Un tiro di Guarigione associato a un farmaco adatto rimuove un livello di Fatica per 4 ore, dopodiché la dipendenza ritorna."
  source: core

- name: Svantaggio - Maggiore/Minore
  subclass: Duro d'Orecchi
  domains: ""
  description: "Il personaggio ha perso in parte o del tutto l'udito. Minore: -4 ai tiri di Percezione basati sull'udito. Maggiore: è del tutto sordo e fallisce automaticamente tutti i suddetti tiri. Dispositivi di supporto riducono la penalità di 2 ma hanno il 50% di probabilità di staccarsi causando una Ferita."
  source: core

- name: Svantaggio - Minore
  subclass: Eccentrico
  domains: ""
  description: "Il personaggio ha qualche tipo di mania che di solito è divertente ma che può anche causare qualche problema (fissazioni sui vestiti dell'avversario, vantarsi della propria cultura, rifiutarsi di mangiare, bere o socializzare con le classi inferiori, ecc.)."
  source: core

- name: Svantaggio - Maggiore
  subclass: Eroico
  domains: ""
  description: "Il personaggio non sa dire di no a una persona in difficoltà. È sempre il primo a lanciarsi dentro un edificio in fiamme, a dare la caccia ai mostri anche quando la ricompensa è minima, e di solito si lascia commuovere dalle storie lacrimevoli."
  source: core

- name: Svantaggio - Minore
  subclass: Esitante
  domains: ""
  description: "Il personaggio, quando si trova sotto stress, rimane imbambolato. In combattimento, deve pescare due Carte Azione e tenere la più bassa. Se ottiene un Jolly può usarlo normalmente. I personaggi Esitanti non possono prendere i Vantaggi Veloce e Nervi Saldi."
  source: core

- name: Svantaggio - Maggiore/Minore
  subclass: Estraneo
  domains: ""
  description: "Il personaggio spicca come diverso in una società composta da pochi tipi di persone. Subisce -2 ai tiri di Persuasione quando interagisce con persone diverse dalla propria categoria o razza. Maggiore: ha pochi o nessun diritto legale nell'area principale della campagna."
  source: core

- name: Svantaggio - Maggiore/Minore
  subclass: Fissazioni
  domains: ""
  description: "Il personaggio crede in qualcosa che la maggior parte delle persone considera bizzarro. Minore: innocue o gestibili. Maggiore: esprime frequentemente le proprie vedute e le conseguenze non sono sempre piacevoli (il governo è manipolato dagli alieni, gli ospedali uccidono, ecc.)."
  source: core

- name: Svantaggio - Maggiore/Minore
  subclass: Fobia
  domains: ""
  description: "Una fobia è una paura irrazionale che perseguita la psiche dell'eroe. Quando si imbatte nell'oggetto della sua paura (di solito vedendola) subisce -1 a tutti i tiri sui Tratti (Minore) o -2 se la Fobia è Maggiore."
  source: core

- name: Svantaggio - Maggiore/Minore
  subclass: Giovane
  domains: ""
  description: "Minore (12-15 anni): riceve solo 4 punti per gli attributi e 10 per le abilità. Maggiore (8-11 anni): 3 punti attributi, 10 abilità, ottiene Svantaggio Piccolo. In entrambi i casi ottiene un Benny aggiuntivo all'inizio di ogni sessione."
  source: core

- name: Svantaggio - Maggiore/Minore
  subclass: Giuramento
  domains: ""
  description: "Il personaggio ha prestato un giuramento solenne. Minore: appartenenza a un ordine con finalità ampie che non entrano in conflitto con gli obiettivi del gruppo. Maggiore: impegni frequenti e a lungo termine che mettono in pericolo la vita stessa del personaggio."
  source: core

- name: Svantaggio - Maggiore
  subclass: Goffo
  domains: ""
  description: "Il personaggio è un pasticcione privo di coordinazione, capace di inciampare nei propri stessi piedi, e viene scelto sempre per ultimo negli sport. Subisce una penalità di -2 ai tiri di Atletica e Furtività."
  source: core

- name: Svantaggio - Maggiore
  subclass: Guercio
  domains: ""
  description: "Il personaggio ha perso un occhio e ha qualche difficoltà a percepire la profondità. Subisce una penalità di -2 ai tiri sui Tratti per le azioni che si basano sulla vista di qualcosa a più di 5\" (10 metri) di distanza."
  source: core

- name: Svantaggio - Maggiore/Minore
  subclass: Implacabile
  domains: ""
  description: "Maggiore: il personaggio è pronto a sacrificare l'incolumità di chiunque si frapponga tra lui e il suo obiettivo. Minore: evita di causare danni fisici ad altri, a meno che non si oppongano apertamente ai suoi piani."
  source: core

- name: Svantaggio - Maggiore
  subclass: Impulsivo
  domains: ""
  description: "Questo scavezzacollo si lancia nell'azione senza riflettere granché. Prima agisce, poi pensa."
  source: core

- name: Svantaggio - Maggiore/Minore
  subclass: Invidioso
  domains: ""
  description: "Minore: l'invidia si focalizza su un solo oggetto in particolare (un interesse romantico, un ambito specifico). Maggiore: è invidioso di chiunque riesca meglio di lui. Non può fare a meno di sparlarne costantemente e può arrivare a tramare per far cadere in disgrazia chiunque minacci il suo ego."
  source: core

- name: Svantaggio - Minore
  subclass: Leale
  domains: ""
  description: "Il personaggio è pronto a rischiare la vita per i suoi amici. Alcuni eroi Leali potrebbero anche non sembrare particolarmente virtuosi, ma sono comunque i primi a lanciarsi in aiuto degli alleati se qualcosa li minaccia."
  source: core

- name: Svantaggio - Maggiore/Minore
  subclass: Lento
  domains: ""
  description: "Il personaggio è rallentato da una disabilità o una vecchia ferita. Minore: Passo -1 e il dado per correre peggiora di un tipo (d4 diventa d4-1). Maggiore: Passo -2, dado per correre peggiora di un tipo, -2 a tutti i tiri di Atletica e ai test contrapposti. I Lenti non possono prendere il Vantaggio Pieveloce."
  source: core

- name: Svantaggio - Maggiore
  subclass: Lingua Attorcigliata
  domains: ""
  description: "Il personaggio si impappina (e soprattutto!) quando cerca di pronunciare una frase a effetto. Tutti i tiri di Intimidire, Esibirsi, Persuasione e Provocare che coinvolgano la comunicazione verbale subiscono una penalità di -1."
  source: core

- name: Svantaggio - Minore
  subclass: Meschino
  domains: ""
  description: "Il personaggio è scorbutico e scontroso. Non riesce a essere gentile e a dare una buona impressione di sé. Sottrae -1 da tutti i tiri di Persuasione."
  source: core

- name: Svantaggio - Minore
  subclass: Mite
  domains: ""
  description: "Il personaggio non riesce ad apparire minaccioso in nessun modo. Forse ha un timbro di voce delicato, o un volto buono, o è d'indole mite. Sottrae -2 da tutti i tiri di Intimidire."
  source: core

- name: Svantaggio - Maggiore
  subclass: Muto
  domains: ""
  description: "Il personaggio non può parlare, forse a causa di un trauma o per motivi congeniti. Può comunicare scrivendo, se necessario, oppure usando il linguaggio dei segni o altre forme di comunicazione visive."
  source: core

- name: Svantaggio - Maggiore/Minore
  subclass: Nemico
  domains: ""
  description: "Qualcuno là fuori odia il personaggio e desidera mandarlo in rovina, farlo rinchiudere o vederlo morto. Minore: un pistolero solitario o una fratellanza tradita che appare raramente. Maggiore: una potente autorità, una banda di fuorilegge, o un singolo rivale pericoloso e spietato."
  source: core

- name: Svantaggio - Minore
  subclass: Non Sa Nuotare
  domains: ""
  description: "Nel ventunesimo secolo la maggior parte delle persone può imparare a nuotare senza difficoltà, ma storicamente chi viveva lontano dalle coste di solito non era in grado. Subisce una penalità di -2 ai tiri di Atletica per nuotare e ogni pollice di spostamento in acqua conta per 3."
  source: core

- name: Svantaggio - Minore
  subclass: Obeso
  domains: ""
  description: "Il personaggio è imponente o molto in forma ma la massa corporea è un impedimento. +1 alla Taglia (e quindi +1 alla Robustezza), ma il Passo è ridotto di 1, il dado per correre peggiora di un tipo (min d4), e la Forza è considerata peggiore di un tipo di dado per armature e indossare equipaggiamento. Non può essere anche Massiccio, né può aumentare la Taglia oltre 3."
  source: core

- name: Svantaggio - Maggiore/Minore
  subclass: Obiettivo
  domains: ""
  description: "Il personaggio si è imposto da solo una meta da raggiungere o un obbligo cui ottemperare (difendere il regno, diventare ufficiale pluridecorato, ecc.). Minore: influenza le decisioni ma raramente crea pericoli concreti. Maggiore: desiderio incontenibile, che spesso entra in gioco e comporta un serio pericolo."
  source: core

- name: Svantaggio - Minore
  subclass: Ostinato
  domains: ""
  description: "Gli individui Ostinati vogliono sempre fare di testa loro e non ammettono mai di avere torto. Anche quando i fatti li smentiscono in maniera evidente, cercano di giustificare i propri errori tramite mezze verità e razionalizzazioni."
  source: core

- name: Svantaggio - Maggiore/Minore
  subclass: Pacifista
  domains: ""
  description: "Il personaggio rifiuta categoricamente la violenza. Minore: combatte solo quando non ha altra scelta e non permette mai che prigionieri o altre vittime indifese vengano uccisi. Maggiore: non combatte contro avversari viventi in nessun caso; può difendersi ma non farebbe mai nulla che possa arrecare danni permanenti a creature viventi e senzienti."
  source: core

- name: Svantaggio - Maggiore/Minore
  subclass: Permaloso
  domains: ""
  description: "Il personaggio è particolarmente suscettibile alle offese. Minore: -2 ai tiri per resistere agli attacchi di Provocare. Maggiore: -4 ai tiri per resistere agli attacchi di Provocare."
  source: core

- name: Svantaggio - Minore
  subclass: Piccolo
  domains: ""
  description: "Rispetto a un umano medio, questo avventuriero è molto magro, molto basso, o entrambe le cose. Ottiene -1 alla Taglia (vedi Taglia) e di conseguenza -1 alla Robustezza."
  source: core

- name: Svantaggio - Minore
  subclass: Povero
  domains: ""
  description: "Il personaggio inizia il gioco con metà dei fondi iniziali previsti dall'ambientazione e sembra non essere in grado di tenersi in tasca il denaro che ottiene: ogni settimana di gioco i suoi fondi si dimezzano."
  source: core

- name: Svantaggio - Maggiore
  subclass: Presuntuoso
  domains: ""
  description: "Là fuori non c'è nulla che il personaggio non possa sconfiggere, o per lo meno questo è ciò che pensa. È convinto di poter fare praticamente tutto e non indietreggia mai davanti a una sfida. Non è un suicida, ma di certo affronta sfide più grandi di quanto suggerirebbe il buon senso."
  source: core

- name: Svantaggio - Maggiore/Minore
  subclass: Responsabilita
  domains: ""
  description: "Il personaggio deve occuparsi di qualcosa o qualcuno quotidianamente o comunque con regolarità (un lavoro, un'attività di volontariato, una famiglia da badare o simili). Minore: circa 20 ore settimanali. Maggiore: circa 40 ore settimanali."
  source: core

- name: Svantaggio - Maggiore/Minore
  subclass: Ricercato
  domains: ""
  description: "Il personaggio ha compiuto qualche genere di crimine e se scoperto verrà arrestato. Minore: accuse minori in un luogo lontano dall'area principale della campagna. Maggiore: essere accusati di omicidio o crimine grave in quasi tutte le ambientazioni."
  source: core

- name: Svantaggio - Maggiore
  subclass: Sanguinario
  domains: ""
  description: "Il personaggio non fa prigionieri, a meno che non sia sotto il controllo diretto di un superiore. La sua indole spietata porta i nemici a fare altrettanto, e spesso può comportare la perdita di informazioni vitali, oltre a creare problemi con i superiori o le autorità."
  source: core

- name: Svantaggio - Minore
  subclass: Scarsa Manualita
  domains: ""
  description: "Il personaggio è del tutto negato quando si tratta di utilizzare dispositivi meccanici o tecnologici. Impone un modificatore di -2 ai tiri associati all'uso di dispositivi meccanici o tecnologici. Se ottieni un Fallimento Critico, l'oggetto che stai utilizzando si rompe (salvo altro effetto previsto). Può essere aggiustato con Riparare."
  source: core

- name: Svantaggio - Minore
  subclass: Scettico
  domains: ""
  description: "Il personaggio cerca in ogni modo di razionalizzare eventi soprannaturali, cercando sempre spiegazioni alternative, e spesso si infila in situazioni pericolose perché si rifiuta di considerarle tali."
  source: core

- name: Svantaggio - Maggiore/Minore
  subclass: Segreto
  domains: ""
  description: "Il personaggio nasconde un segreto che potrebbe mettere in pericolo lui stesso o altre persone. Minore: le conseguenze del segreto sono problematiche ma non rappresentano una minaccia mortale. Maggiore: la divulgazione comporta conseguenze gravi; lo Svantaggio dovrebbe trasformarsi in Nemico, Ricercato, Vergogna o altro Svantaggio appropriato."
  source: core

- name: Svantaggio - Maggiore
  subclass: Sfortuna
  domains: ""
  description: "Il personaggio è un po' meno fortunato degli altri e ottiene un Benny in meno all'inizio di ogni sessione. Non puoi avere Sfortuna se possiedi il Vantaggio Fortuna e viceversa."
  source: core

- name: Svantaggio - Maggiore/Minore
  subclass: Sospettoso
  domains: ""
  description: "Il personaggio sospetta di chiunque. Minore: l'eroe non si fida di nessuno; potrebbe richiedere pagamenti anticipati, accettare accordi solo in forma scritta e convincersi che persino i suoi amici stiano tramando per tradirlo. Maggiore: i tiri di Supporto per aiutare il Sospettoso subiscono una penalità di -2."
  source: core

- name: Svantaggio - Maggiore
  subclass: Svampito
  domains: ""
  description: "Il personaggio non presta molta attenzione al mondo intorno a sé e spesso si perde in un bicchier d'acqua. I suoi tiri di Conoscenze Comuni e Percezione subiscono una penalità di -1."
  source: core

- name: Svantaggio - Maggiore
  subclass: Un Braccio Solo
  domains: ""
  description: "Il personaggio si ritrova con un solo braccio. Per fortuna, quello rimasto è 'quello buono'. I compiti che richiedono due mani (molte delle azioni risolte con Atletica, o l'uso di armi a due mani) subiscono una penalità di -4."
  source: core

- name: Svantaggio - Maggiore/Minore
  subclass: Vendicativo
  domains: ""
  description: "Il personaggio cerca la vendetta. Minore: ricerca la vendetta entro i limiti della legge. Maggiore: la resa dei conti diventa una priorità imprescindibile; non si fermerà finché il torto subito non sia stato reso."
  source: core

- name: Svantaggio - Maggiore/Minore
  subclass: Vergogna
  domains: ""
  description: "Un evento passato tormenta il personaggio. Minore: lo tormenta nei ricordi e lo rende pronto a tutto pur di non ripetere lo stesso errore. Maggiore: l'evento è ben noto almeno alle persone a cui l'eroe tiene di più; l'onta può essere utilizzata contro di lui per screditarlo o metterlo in difficoltà."
  source: core

- name: Svantaggio - Maggiore
  subclass: Vigliacco
  domains: ""
  description: "L'eroe non supporta la vista del sangue, teme la violenza ed è terrorizzato all'idea di essere ferito. Subisce -2 dai tiri per resistere alla Paura e a Intimidire."
  source: core

- name: Svantaggio - Maggiore/Minore
  subclass: Vista Difettosa
  domains: ""
  description: "Gli occhi del personaggio non funzionano più bene come una volta. Minore: -1 a tutti i tiri sui Tratti dipendenti dalla vista e ai tiri di Percezione e attacchi a distanza. Maggiore: -2. Gli occhiali sono sufficienti a rimuovere la penalità, ma in combattimento c'è il 50% di probabilità che si rompano."
  source: core
