- name: Giacca di cuoio
  category: Armature
  type: Cuoio/Tessuto
  rank: 1
  era: Antica/Moderna
  cost: "100"
  weight: "3"
  min_strength: d4
  armor: "+1"
  note: "Tronco, braccia"

- name: Veste di cuoio
  category: Armature
  type: Cuoio/Tessuto
  rank: 1
  era: Antica
  cost: "30"
  weight: "4"
  min_strength: d4
  armor: "+1"
  note: "Tronco, braccia, gambe"

- name: Giacca in kevlar
  category: Armature
  type: Cuoio/Tessuto
  rank: 2
  era: Moderna
  cost: "350"
  weight: "4"
  min_strength: d4
  armor: "+2"
  note: "Tronco, braccia"

- name: Veste in kevlar
  category: Armature
  type: Protezioni
  rank: 2
  era: Moderna
  cost: "200"
  weight: "2.5"
  min_strength: d6
  armor: "+2*"
  note: "Riduce di 4 i danni da armi da fuoco"

- name: Veste kevlar con ceramica
  category: Armature
  type: Protezioni
  rank: 2
  era: Moderna
  cost: "500"
  weight: "8.5"
  min_strength: d8
  armor: "+4*"
  note: "Tronco"

- name: Tuta anti-esplosivi
  category: Armature
  type: Protezioni
  rank: 2
  era: Moderna
  cost: "25000"
  weight: "40"
  min_strength: d12
  armor: "+10"
  note: "Passo -2, Agilita limitata al d6"

- name: Corazza da fanteria
  category: Armature
  type: Militare
  rank: 3
  era: Futuristica
  cost: "800"
  weight: "6"
  min_strength: d6
  armor: "+6*"
  note: "Tronco, braccia, gambe"

- name: Elmo da battaglia (chiuso)
  category: Armature
  type: Militare
  rank: 3
  era: Futuristica
  cost: "100"
  weight: "1"
  min_strength: d6
  armor: "+6*"

- name: Scudo piccolo
  category: Scudi
  type: Antico/Medievale
  rank: 1
  era: Antica
  cost: "50"
  weight: "2"
  min_strength: d4
  parry: "+1"
  cover: "-"

- name: Scudo medio
  category: Scudi
  type: Antico/Medievale
  rank: 1
  era: Antica
  cost: "100"
  weight: "4"
  min_strength: d6
  parry: "+2"
  cover: "-2"

- name: Scudo grande
  category: Scudi
  type: Antico/Medievale
  rank: 1
  era: Antica
  cost: "200"
  weight: "6"
  min_strength: d8
  parry: "+3"
  cover: "-4"

- name: Scudo antisommossa
  category: Scudi
  type: Moderno
  rank: 2
  era: Moderna
  cost: "80"
  weight: "2.5"
  min_strength: d4
  parry: "+3"
  cover: "-4"

- name: Scudo antiproiettile
  category: Scudi
  type: Moderno
  rank: 2
  era: Moderna
  cost: "250"
  weight: "4.5"
  min_strength: d6
  parry: "+3"
  cover: "-4"
  note: "Riduce di 4 i danni da armi da fuoco dal fronte/lato"

- name: Ascia
  category: Armi da Mischia
  type: Antica/Medievale
  rank: 1
  era: Antica
  cost: "100"
  weight: "1"
  min_strength: d6
  damage: For+d6

- name: Ascia da battaglia
  category: Armi da Mischia
  type: Antica/Medievale
  rank: 1
  era: Antica
  cost: "300"
  weight: "2"
  min_strength: d8
  damage: For+d8

- name: Ascia a due mani
  category: Armi da Mischia
  type: Antica/Medievale
  rank: 1
  era: Antica
  cost: "400"
  weight: "3.5"
  min_strength: d10
  damage: For+d10
  ap: "2"
  note: "Parata -1, due mani"

- name: Bastone
  category: Armi da Mischia
  type: Antica/Medievale
  rank: 1
  era: Antica
  cost: "10"
  weight: "2"
  min_strength: d4
  damage: For+d4
  note: "Parata +1, Portata 1, due mani"

- name: Lancia
  category: Armi da Mischia
  type: Antica/Medievale
  rank: 1
  era: Antica
  cost: "100"
  weight: "1.5"
  min_strength: d6
  damage: For+d6
  note: "Portata 1; Parata +1 se a due mani"

- name: Martello da guerra
  category: Armi da Mischia
  type: Antica/Medievale
  rank: 1
  era: Antica
  cost: "250"
  weight: "1"
  min_strength: d6
  damage: For+d6
  ap: "1"
  note: "Becco di corvo"

- name: Spada lunga
  category: Armi da Mischia
  type: Antica/Medievale
  rank: 1
  era: Antica
  cost: "300"
  weight: "1.5"
  min_strength: d8
  damage: For+d8

- name: Spadone
  category: Armi da Mischia
  type: Antica/Medievale
  rank: 1
  era: Antica
  cost: "400"
  weight: "3"
  min_strength: d10
  damage: For+d10
  note: "Due mani"

- name: Pugnale/Coltello
  category: Armi da Mischia
  type: Antica/Medievale
  rank: 1
  era: Antica
  cost: "25"
  weight: "0.5"
  min_strength: d4
  damage: For+d4

- name: Manganello
  category: Armi da Mischia
  type: Moderna
  rank: 2
  era: Moderna
  cost: "10"
  weight: "0.5"
  min_strength: d4
  damage: For+d4

- name: Motosega
  category: Armi da Mischia
  type: Moderna
  rank: 2
  era: Moderna
  cost: "200"
  weight: "10"
  min_strength: d6
  damage: 2d6+4
  note: "Con Fallimento Critico colpisce l'attaccante"

- name: Tirapugni
  category: Armi da Mischia
  type: Moderna
  rank: 2
  era: Moderna
  cost: "20"
  weight: "0.5"
  min_strength: d4
  damage: For+d4
  note: "Non conta come arma per Difensore senza Armi"

- name: Spada laser
  category: Armi da Mischia
  type: Futuristica
  rank: 3
  era: Futuristica
  cost: "1000"
  weight: "1"
  min_strength: d4
  damage: For+d6+8
  ap: "12"

- name: Arco
  category: Armi a Distanza
  type: Antica/Medievale
  rank: 1
  era: Antica
  cost: "250"
  weight: "1.5"
  min_strength: d6
  range: 12/24/48
  damage: 2d6
  rof: "1"

- name: Arco lungo
  category: Armi a Distanza
  type: Antica/Medievale
  rank: 1
  era: Antica
  cost: "300"
  weight: "1.5"
  min_strength: d8
  range: 15/30/60
  damage: 2d6
  ap: "1"
  rof: "1"

- name: Balestra
  category: Armi a Distanza
  type: Antica/Medievale
  rank: 1
  era: Antica
  cost: "250"
  weight: "2.5"
  min_strength: d6
  range: 10/20/40
  damage: 2d6
  ap: "2"
  rof: "1"
  note: "Ricarica a mano"

- name: Balestra pesante
  category: Armi a Distanza
  type: Antica/Medievale
  rank: 1
  era: Antica
  cost: "400"
  weight: "4"
  min_strength: d6
  range: 15/30/60
  damage: 2d8
  ap: "2"
  rof: "1"
  note: "Ricarica 2 (argano)"

- name: Pistola ad acciarino
  category: Armi da Fuoco
  type: Polvere nera
  rank: 1
  era: Polvere nera
  cost: "150"
  weight: "1.5"
  min_strength: d4
  range: 5/10/20
  damage: 2d6+1
  rof: "1"
  shots: "-"
  note: "Ricarica 3"

- name: Brown Bess
  category: Armi da Fuoco
  type: Polvere nera
  rank: 1
  era: Polvere nera
  cost: "300"
  weight: "7.5"
  min_strength: d6
  range: 10/20/40
  damage: 2d8
  rof: "1"
  shots: "-"
  note: "Ricarica 3"

- name: Colt Peacemaker (.45)
  category: Armi da Fuoco
  type: Revolver
  rank: 2
  era: Moderna
  cost: "200"
  weight: "2"
  min_strength: d4
  range: 12/24/48
  damage: 2d6+1
  ap: "1"
  rof: "1"
  shots: "6"

- name: Derringer (.41)
  category: Armi da Fuoco
  type: Revolver
  rank: 2
  era: Moderna
  cost: "100"
  weight: "0.5"
  min_strength: d4
  range: 3/6/12
  damage: 2d4
  rof: "1"
  shots: "2"
  note: "-2 Percezione se nascosta"

- name: Revolver da polizia (.38)
  category: Armi da Fuoco
  type: Revolver
  rank: 2
  era: Moderna
  cost: "150"
  weight: "1"
  min_strength: d4
  range: 10/20/40
  damage: 2d6
  rof: "1"
  shots: "6"

- name: Colt 1911 (.45)
  category: Armi da Fuoco
  type: Semiautomatica
  rank: 2
  era: Moderna
  cost: "200"
  weight: "2"
  min_strength: d4
  range: 12/24/48
  damage: 2d6+1
  ap: "1"
  rof: "1"
  shots: "7"

- name: Desert Eagle (.50)
  category: Armi da Fuoco
  type: Semiautomatica
  rank: 2
  era: Moderna
  cost: "300"
  weight: "4"
  min_strength: d6
  range: 15/30/60
  damage: 2d8
  ap: "2"
  rof: "1"
  shots: "7"

- name: Glock (9mm)
  category: Armi da Fuoco
  type: Semiautomatica
  rank: 2
  era: Moderna
  cost: "200"
  weight: "1.5"
  min_strength: d4
  range: 12/24/48
  damage: 2d6
  ap: "1"
  rof: "1"
  shots: "17"

- name: H&K MP5 (9mm)
  category: Armi da Fuoco
  type: Mitra
  rank: 2
  era: Moderna
  cost: "300"
  weight: "5"
  min_strength: d6
  range: 12/24/48
  damage: 2d6
  ap: "1"
  rof: "3"
  shots: "30"

- name: Thompson (.45)
  category: Armi da Fuoco
  type: Mitra
  rank: 2
  era: Moderna
  cost: "350"
  weight: "6.5"
  min_strength: d6
  range: 12/24/48
  damage: 2d6+1
  ap: "1"
  rof: "3"
  shots: "20"

- name: Uzi (9mm)
  category: Armi da Fuoco
  type: Mitra
  rank: 2
  era: Moderna
  cost: "300"
  weight: "4.5"
  min_strength: d4
  range: 12/24/48
  damage: 2d6
  ap: "1"
  rof: "3"
  shots: "32"

- name: Frecce/dardi (10)
  category: Munizioni
  type: Arco/Balestra
  rank: 1
  era: Antica
  cost: "5"
  weight: "1"
  note: "Per archi/balestre"

- name: Proiettili piccoli (50)
  category: Munizioni
  type: Pistola/Fucile leggero
  rank: 2
  era: Moderna
  cost: "10"
  weight: "0.5"

- name: Proiettili medi (50)
  category: Munizioni
  type: Pistola/Fucile medio
  rank: 2
  era: Moderna
  cost: "20"
  weight: "1"

- name: Proiettili grandi (50)
  category: Munizioni
  type: Calibro .50+
  rank: 2
  era: Moderna
  cost: "50"
  weight: "7"

- name: Cartucce shotgun pallettoni (50)
  category: Munizioni
  type: Shotgun
  rank: 2
  era: Moderna
  cost: "30"
  weight: "1.5"

- name: Cartucce shotgun proiettile (50)
  category: Munizioni
  type: Shotgun
  rank: 2
  era: Moderna
  cost: "40"
  weight: "1.5"
  note: "Vedi regole shotgun"

- name: Razioni da viaggio
  category: Generi
  type: Cibo
  rank: 1
  era: Generica
  cost: "10"
  weight: "2.5"
  note: "5 pasti, si conservano per 1 settimana"

- name: Razioni militari (MRE)
  category: Generi
  type: Cibo
  rank: 2
  era: Moderna
  cost: "10"
  weight: "0.5"

- name: Visore notturno
  category: Attrezzatura
  type: Elettronica
  rank: 2
  era: Moderna
  cost: "500"
  weight: "1.5"
  note: "Annulla penalita da Illuminazione Fioca/Buio"
- name: A pompa
  category: Armi da Fuoco
  type: Shotgun
  rank: 2
  era: Moderna
  cost: "150"
  weight: "4"
  min_strength: d4
  range: 12/24/48
  damage: 1-3d6
  rof: "1"
  shots: "6"

- name: Doppietta
  category: Armi da Fuoco
  type: Shotgun
  rank: 2
  era: Moderna
  cost: "150"
  weight: "5.5"
  min_strength: d6
  range: 12/24/48
  damage: 1-3d6
  rof: "1"
  shots: "2"

- name: Doppietta canne mozze
  category: Armi da Fuoco
  type: Shotgun
  rank: 2
  era: Moderna
  cost: "150"
  weight: "3"
  min_strength: d4
  range: 5/10/20
  damage: 1-3d6
  rof: "1"
  shots: "2"

- name: Streetsweeper (Armsel Striker)
  category: Armi da Fuoco
  type: Shotgun
  rank: 2
  era: Moderna
  cost: "450"
  weight: "5"
  min_strength: d6
  range: 12/24/48
  damage: 1-3d6
  rof: "1"
  shots: "12"

- name: Barrett (.50)
  category: Armi da Fuoco
  type: Fucile
  rank: 2
  era: Moderna
  cost: "750"
  weight: "17.5"
  min_strength: d8
  range: 50/100/200
  damage: 2d10
  ap: "4"
  rof: "1"
  shots: "10"
  note: "Arma Pesante, Bruciapelo"

- name: Carabina Spencer (.52)
  category: Armi da Fuoco
  type: Fucile
  rank: 2
  era: Polvere nera
  cost: "250"
  weight: "4"
  min_strength: d4
  range: 20/40/80
  damage: 2d8
  ap: "2"
  rof: "1"
  shots: "7"

- name: Fucile da caccia (.308)
  category: Armi da Fuoco
  type: Fucile
  rank: 2
  era: Moderna
  cost: "350"
  weight: "4"
  min_strength: d6
  range: 24/48/96
  damage: 2d8
  ap: "2"
  rof: "1"
  shots: "5"
  note: "Bruciapelo"

- name: M1 Garand (.30-06)
  category: Armi da Fuoco
  type: Fucile
  rank: 2
  era: Moderna
  cost: "300"
  weight: "5"
  min_strength: d6
  range: 24/48/96
  damage: 2d8
  ap: "2"
  rof: "1"
  shots: "8"

- name: Sharps Big 50 (.50)
  category: Armi da Fuoco
  type: Fucile
  rank: 2
  era: Polvere nera
  cost: "400"
  weight: "5.5"
  min_strength: d8
  range: 30/60/120
  damage: 2d10
  ap: "2"
  rof: "1"
  shots: "1"
  note: "Bruciapelo"

- name: Winchester '73 (.44-40)
  category: Armi da Fuoco
  type: Fucile
  rank: 2
  era: Polvere nera
  cost: "300"
  weight: "5"
  min_strength: d6
  range: 24/48/96
  damage: 2d8-1
  ap: "2"
  rof: "1"
  shots: "15"

- name: AK47 (7.62mm)
  category: Armi da Fuoco
  type: Fucile d'assalto
  rank: 2
  era: Moderna
  cost: "450"
  weight: "5"
  min_strength: d6
  range: 24/48/96
  damage: 2d8+1
  ap: "2"
  rof: "3"
  shots: "30"

- name: M-16 (5.56mm)
  category: Armi da Fuoco
  type: Fucile d'assalto
  rank: 2
  era: Moderna
  cost: "400"
  weight: "4"
  min_strength: d6
  range: 24/48/96
  damage: 2d8
  ap: "2"
  rof: "3"
  shots: "20/30"
  note: "A-2: anche Raffica da Tre Colpi"

- name: Steyr AUG (5.56mm)
  category: Armi da Fuoco
  type: Fucile d'assalto
  rank: 2
  era: Moderna
  cost: "400"
  weight: "4"
  min_strength: d6
  range: 24/48/96
  damage: 2d8
  ap: "2"
  rof: "3"
  shots: "30"
  note: "Anche Raffica da Tre Colpi"

- name: Browning Automatic Rifle (BAR)
  category: Armi da Fuoco
  type: Mitragliatrice
  rank: 2
  era: Moderna
  cost: "300"
  weight: "8.5"
  min_strength: d8
  range: 20/40/60
  damage: 2d8
  ap: "2"
  rof: "3"
  shots: "20"
  note: "CdT 1-3, Ricarica 1"

- name: Gatling (.45)
  category: Armi da Fuoco
  type: Mitragliatrice
  rank: 2
  era: Moderna
  cost: "500"
  weight: "85"
  min_strength: NA
  range: 24/48/96
  damage: 2d8
  ap: "2"
  rof: "3"
  shots: "100"

- name: Minigun (7.62mm)
  category: Armi da Fuoco
  type: Mitragliatrice
  rank: 3
  era: Moderna
  cost: "100K"
  weight: "42.5"
  min_strength: d10
  range: 30/60/120
  damage: 2d8+1
  ap: "2"
  rof: "5"
  shots: "4000"
  note: "CdT minima 3; zaino munizioni +42.5kg"

- name: M2 Browning (.50)
  category: Armi da Fuoco
  type: Mitragliatrice
  rank: 3
  era: Moderna
  cost: "1500"
  weight: "42"
  min_strength: NA
  range: 50/100/200
  damage: 2d10
  ap: "4"
  rof: "3"
  shots: "200"
  note: "Arma Pesante"

- name: M60 (7.62mm)
  category: Armi da Fuoco
  type: Mitragliatrice
  rank: 2
  era: Moderna
  cost: "6000"
  weight: "16.5"
  min_strength: d8
  range: 30/60/120
  damage: 2d8+1
  ap: "2"
  rof: "3"
  shots: "100"

- name: MG42 (7.62mm)
  category: Armi da Fuoco
  type: Mitragliatrice
  rank: 2
  era: Moderna
  cost: "750"
  weight: "13"
  min_strength: d10
  range: 30/60/120
  damage: 2d8+1
  ap: "2"
  rof: "4"
  shots: "200"

- name: SAW (5.56mm)
  category: Armi da Fuoco
  type: Mitragliatrice
  rank: 2
  era: Moderna
  cost: "4000"
  weight: "10"
  min_strength: d8
  range: 30/60/120
  damage: 2d8
  ap: "2"
  rof: "4"
  shots: "200"

- name: Pistola laser
  category: Armi da Fuoco
  type: Laser
  rank: 3
  era: Futuristica
  cost: "250"
  weight: "1"
  min_strength: d4
  range: 15/30/60
  damage: 2d6
  ap: "2"
  rof: "1"
  shots: "50"
  note: "+2 Vigore contro Dissanguamento; opzione sovraccarico +1d6"

- name: Mitra laser
  category: Armi da Fuoco
  type: Laser
  rank: 3
  era: Futuristica
  cost: "500"
  weight: "2"
  min_strength: d4
  range: 15/30/60
  damage: 2d6
  ap: "2"
  rof: "4"
  shots: "100"

- name: Fucile laser
  category: Armi da Fuoco
  type: Laser
  rank: 3
  era: Futuristica
  cost: "700"
  weight: "4"
  min_strength: d6
  range: 30/60/120
  damage: 3d6
  ap: "2"
  rof: "3"
  shots: "100"

- name: Gatling laser
  category: Armi da Fuoco
  type: Laser
  rank: 3
  era: Futuristica
  cost: "1000"
  weight: "10"
  min_strength: d8
  range: 50/100/200
  damage: 3d6+4
  ap: "2"
  rof: "4"
  shots: "800"

- name: Lanciafiamme
  category: Armi Speciali
  type: Lanciafiamme
  rank: 3
  era: Moderna
  cost: "300"
  weight: "35"
  min_strength: d8
  range: Modello Conico
  damage: 3d6
  rof: "1"
  shots: "10"
  note: "Arma Pesante"

- name: Mk II "ananas"
  category: Armi Speciali
  type: Granata
  rank: 2
  era: Moderna
  cost: "40"
  weight: "0.5"
  range: 4/8/16
  damage: 3d6
  rof: "-"
  note: "Modello Esplosione Media; Arma Pesante"

- name: "Schiacciapatate (2a Guerra)"
  category: Armi Speciali
  type: Granata
  rank: 2
  era: Moderna
  cost: "50"
  weight: "1"
  range: 5/10/20
  damage: 3d6-2
  rof: "-"
  note: "Modello Esplosione Media; Arma Pesante"

- name: Mk67 (moderna)
  category: Armi Speciali
  type: Granata
  rank: 2
  era: Moderna
  cost: "50"
  weight: "0.5"
  range: 5/10/20
  damage: 3d6
  rof: "-"
  note: "Modello Esplosione Media; Arma Pesante"

- name: Granata fumogena
  category: Armi Speciali
  type: Granata
  rank: 2
  era: Moderna
  cost: "50"
  weight: "0.5"
  range: 5/10/20
  damage: "-"
  rof: "-"
  note: "Crea area fumo (MEG), -4 ai tiri attraverso"

- name: Granata stordente
  category: Armi Speciali
  type: Granata
  rank: 2
  era: Moderna
  cost: "50"
  weight: "0.5"
  range: 5/10/20
  damage: "-"
  rof: "-"
  note: "Vigore o Stordito (a -2 con incremento)"

- name: Mina antiuomo
  category: Armi Speciali
  type: Mina
  rank: 2
  era: Moderna
  cost: "100"
  weight: "5"
  range: "-"
  damage: 2d6+2
  rof: "-"
  note: "Arma Pesante; MEP"

- name: Mina anticarro
  category: Armi Speciali
  type: Mina
  rank: 3
  era: Moderna
  cost: "200"
  weight: "10"
  range: "-"
  damage: 4d6
  ap: "5"
  rof: "-"
  note: "Arma Pesante; contro armatura piu bassa del veicolo"

- name: Hellfire
  category: Armi Speciali
  type: Missile
  rank: 4
  era: Moderna
  cost: "115K"
  weight: "50"
  range: 150/300/600
  damage: 5d10
  ap: "40"
  rof: "-"
  note: "Arma Pesante, guida laser, MEM"

- name: Sidewinder
  category: Armi Speciali
  type: Missile
  rank: 4
  era: Moderna
  cost: "600K"
  weight: "94"
  range: 100/200/400
  damage: 4d8
  ap: "6"
  rof: "-"
  note: "Arma Pesante, ricerca calore, MEP"

- name: Sparrow
  category: Armi Speciali
  type: Missile
  rank: 4
  era: Moderna
  cost: "125K"
  weight: "308"
  range: 150/300/600
  damage: 5d8
  ap: "6"
  rof: "-"
  note: "Arma Pesante, guida radar, MEP"

- name: TOW
  category: Armi Speciali
  type: Missile
  rank: 4
  era: Moderna
  cost: "60K"
  weight: "103"
  range: 75/150/300
  damage: 5d10
  ap: "34"
  rof: "1"
  note: "Arma Pesante, filoguidato, MEM"

- name: AT-4
  category: Armi Speciali
  type: Lanciarazzi
  rank: 3
  era: Moderna
  cost: "1500"
  weight: "7.5"
  range: 24/48/96
  damage: 4d8+2
  ap: "24"
  rof: "1"
  note: "Anticarro, MEM"

- name: Bazooka
  category: Armi Speciali
  type: Lanciarazzi
  rank: 3
  era: Moderna
  cost: "500"
  weight: "6"
  range: 24/48/96
  damage: 4d8
  ap: "8"
  rof: "1"
  note: "Bruciapelo, MEM"

- name: M72 LAW
  category: Armi Speciali
  type: Lanciarazzi
  rank: 3
  era: Moderna
  cost: "750"
  weight: "2.5"
  range: 24/48/96
  damage: 4d8+2
  ap: "22"
  rof: "1"
  note: "Arma Pesante, Bruciapelo, MEM"

- name: Panzerschreck
  category: Armi Speciali
  type: Lanciarazzi
  rank: 3
  era: Moderna
  cost: "1000"
  weight: "10"
  range: 15/30/60
  damage: 4d8
  ap: "12"
  rof: "1"
  note: "Bruciapelo, MEM"

- name: Cannone 12 libbre
  category: Armi Speciali
  type: Cannone
  rank: 3
  era: Antica/Moderna
  cost: "10K"
  weight: "600"
  range: Varia per munizione
  damage: In base alle munizioni
  rof: "1"
  note: "Ricarica 8"

- name: Catapulta
  category: Armi Speciali
  type: Artiglieria
  rank: 2
  era: Antica
  cost: "10K"
  range: 24/48/96
  damage: 3d6
  ap: "4"
  rof: Speciale
  note: "Arma Pesante, MEM, ricarica 5 minuti"

- name: Trabucco
  category: Armi Speciali
  type: Artiglieria
  rank: 2
  era: Antica
  cost: "50K"
  range: 30/60/120
  damage: 3d8
  ap: "4"
  rof: Speciale
  note: "Arma Pesante, MEM, ricarica 5 minuti"
