// Code generated by xsdgen. DO NOT EDIT.

package model

import (
	"bytes"
	"encoding/xml"
	"time"
)

type BOINBALANCE struct {
	GROUPING StrMxLn1 `xml:"http://www.csc.com/stealth3000 GROUPING"`
}

type DETTBMGC struct {
	BMGC []TBMGC `xml:"http://www.csc.com/stealth3000 BMGC,omitempty"`
}

type DETTBMGP struct {
	BMGP []TBMGP `xml:"http://www.csc.com/stealth3000 BMGP,omitempty"`
}

type DETTBMGPVALASSOC struct {
	BMGPVALASSOC []TBMGPVALASSOC `xml:"http://www.csc.com/stealth3000 BMGP_VAL_ASSOC,omitempty"`
}

type DETTBMGR struct {
	BMGR []TBMGR `xml:"http://www.csc.com/stealth3000 BMGR,omitempty"`
}

type DETTBMGRAGE struct {
	BMGRAGE []TBMGRAGE `xml:"http://www.csc.com/stealth3000 BMGR_AGE,omitempty"`
}

type DETTBMGRAGEPRV struct {
	BMGRAGEPRV []TBMGRAGEPRV `xml:"http://www.csc.com/stealth3000 BMGR_AGE_PRV,omitempty"`
}

type DETTBMGRASSOC struct {
	BMGRASSOC []TBMGRASSOC `xml:"http://www.csc.com/stealth3000 BMGR_ASSOC,omitempty"`
}

type DETTBMGRBAR struct {
	BMGRBAR []TBMGRBAR `xml:"http://www.csc.com/stealth3000 BMGR_BAR,omitempty"`
}

type DETTBMGRBARASSOC struct {
	BMGRBARASSOC []TBMGRBAR `xml:"http://www.csc.com/stealth3000 BMGR_BAR_ASSOC,omitempty"`
}

type DETTBMGRCDS struct {
	BMGRCDS []TBMGRCDS `xml:"http://www.csc.com/stealth3000 BMGR_CDS,omitempty"`
}

type DETTBMGRCDSCPRTGL struct {
	BMGRCDSCPRTGL []TBMGRCDSCPRTGL `xml:"http://www.csc.com/stealth3000 BMGR_CDS_CPR_TGL,omitempty"`
}

type DETTBMGRGRTFPR struct {
	BMGRGRTFPR []TBMGRGRTFPR `xml:"http://www.csc.com/stealth3000 BMGR_GRT_FPR,omitempty"`
}

type DETTBMGRNOT struct {
	BMGRNOT []TNOT `xml:"http://www.csc.com/stealth3000 BMGR_NOT,omitempty"`
}

type DETTBMGRTGL struct {
	BMGRTGL []TBMGRTGL `xml:"http://www.csc.com/stealth3000 BMGR_TGL,omitempty"`
}

type DETTBMGRTGLASSOC struct {
	BMGRTGLASSOC []TBMGRTGLASSOC `xml:"http://www.csc.com/stealth3000 BMGR_TGL_ASSOC,omitempty"`
}

type DETTBMGTASSOC struct {
	BMGTASSOC []TBMGTASSOC `xml:"http://www.csc.com/stealth3000 BMGT_ASSOC,omitempty"`
}

type DETTBMGTLNI struct {
	BMGTLNI []TBMGTLNI `xml:"http://www.csc.com/stealth3000 BMGT_LNI,omitempty"`
}

type DETTBMGTNOT struct {
	BMGTNOT []TNOT `xml:"http://www.csc.com/stealth3000 BMGT_NOT,omitempty"`
}

type DETTBMGTSPE struct {
	BMGTSPE []TBMGTSPE `xml:"http://www.csc.com/stealth3000 BMGT_SPE,omitempty"`
}

type Date string

type DateNotNull time.Time

func (t *DateNotNull) UnmarshalText(text []byte) error {
	return (*xsdDate)(t).UnmarshalText(text)
}
func (t DateNotNull) MarshalText() ([]byte, error) {
	return xsdDate(t).MarshalText()
}

type DateTime string

type DateTimeNotNull time.Time

func (t *DateTimeNotNull) UnmarshalText(text []byte) error {
	return (*xsdDateTime)(t).UnmarshalText(text)
}
func (t DateTimeNotNull) MarshalText() ([]byte, error) {
	return xsdDateTime(t).MarshalText()
}

type Dec string

type Dec105 string

type Dec107 string

type Dec112 string

type Dec123 string

type Dec132 string

type Dec138 string

type Dec1510 string

type Dec153 string

type Dec173 string

type Dec175 string

type Dec183 string

type Dec203 string

type Dec52 string

type Dec53 string

type Dec62 string

type Dec63 string

type Dec72 string

type Dec73 string

type Dec93 string

// May be one of
type EnumNull string

type LISTMESSAGE struct {
	MESSAGE []TMessage `xml:"http://www.csc.com/stealth3000 MESSAGE"`
}

type ORIGDATAAREA struct {
	Item string `xml:",any"`
}

type StrFlag string

// May be one of 0, 1
type StrFlagNotNull string

// May be no more than 1 items long
type StrMxLn1 string

// May be no more than 10 items long
type StrMxLn10 string

// May be no more than 100 items long
type StrMxLn100 string

// May be no more than 1000 items long
type StrMxLn1000 string

// May be no more than 12 items long
type StrMxLn12 string

// May be no more than 15 items long
type StrMxLn15 string

// May be no more than 16 items long
type StrMxLn16 string

// May be no more than 18 items long
type StrMxLn18 string

// May be no more than 190 items long
type StrMxLn190 string

// May be no more than 2 items long
type StrMxLn2 string

// May be no more than 20 items long
type StrMxLn20 string

// May be no more than 200 items long
type StrMxLn200 string

// May be no more than 2000 items long
type StrMxLn2000 string

// May be no more than 24 items long
type StrMxLn24 string

// May be no more than 25 items long
type StrMxLn25 string

// May be no more than 2500 items long
type StrMxLn2500 string

// May be no more than 255 items long
type StrMxLn255 string

// May be no more than 256 items long
type StrMxLn256 string

// May be no more than 3 items long
type StrMxLn3 string

// May be no more than 30 items long
type StrMxLn30 string

// May be no more than 300 items long
type StrMxLn300 string

// May be no more than 32 items long
type StrMxLn32 string

// May be no more than 36 items long
type StrMxLn36 string

// May be no more than 4 items long
type StrMxLn4 string

// May be no more than 400 items long
type StrMxLn400 string

// May be no more than 4000 items long
type StrMxLn4000 string

// May be no more than 42 items long
type StrMxLn42 string

// May be no more than 5 items long
type StrMxLn5 string

// May be no more than 50 items long
type StrMxLn50 string

// May be no more than 500 items long
type StrMxLn500 string

// May be no more than 6 items long
type StrMxLn6 string

// May be no more than 60 items long
type StrMxLn60 string

// May be no more than 7 items long
type StrMxLn7 string

type TApplicationArea struct {
	SENDER        TSender    `xml:"http://www.csc.com/stealth3000 SENDER,omitempty"`
	DATACREAZIONE DateTime   `xml:"http://www.csc.com/stealth3000 DATA_CREAZIONE,omitempty"`
	IDDOCUMENTO   StrMxLn30  `xml:"http://www.csc.com/stealth3000 ID_DOCUMENTO,omitempty"`
	BOCOD         StrMxLn100 `xml:"http://www.csc.com/stealth3000 BO_COD,omitempty"`
	F1            StrMxLn100 `xml:"http://www.csc.com/stealth3000 F1,omitempty"`
	F2            StrMxLn100 `xml:"http://www.csc.com/stealth3000 F2,omitempty"`
	F3            StrMxLn100 `xml:"http://www.csc.com/stealth3000 F3,omitempty"`
	F4            StrMxLn100 `xml:"http://www.csc.com/stealth3000 F4,omitempty"`
	F5            StrMxLn100 `xml:"http://www.csc.com/stealth3000 F5,omitempty"`
}

type TBD struct {
	APPLICATIONAREA TApplicationArea `xml:"http://www.csc.com/stealth3000 APPLICATIONAREA"`
}

// XXX
type TBMGC struct {
	MGCORD     int    `xml:"http://www.csc.com/stealth3000 MGC_ORD,omitempty"`
	MGCPRC     Dec63  `xml:"http://www.csc.com/stealth3000 MGC_PRC,omitempty"`
	MGCDATAINS string `xml:"http://www.csc.com/stealth3000 MGC_DATA_INS,omitempty"`
	MGCDATAMOD string `xml:"http://www.csc.com/stealth3000 MGC_DATA_MOD,omitempty"`
	MGCOPERINS string `xml:"http://www.csc.com/stealth3000 MGC_OPER_INS,omitempty"`
	MGCOPERMOD string `xml:"http://www.csc.com/stealth3000 MGC_OPER_MOD,omitempty"`
	MGCPRGINS  string `xml:"http://www.csc.com/stealth3000 MGC_PRG_INS,omitempty"`
	MGCPRGMOD  string `xml:"http://www.csc.com/stealth3000 MGC_PRG_MOD,omitempty"`
	MGCSOCINS  string `xml:"http://www.csc.com/stealth3000 MGC_SOC_INS,omitempty"`
}

// XXX
type TBMGP struct {
	MGPGRTCOD  StrMxLn10 `xml:"http://www.csc.com/stealth3000 MGP_GRT_COD,omitempty"`
	MGPTGLCOD  StrMxLn6  `xml:"http://www.csc.com/stealth3000 MGP_TGL_COD,omitempty"`
	MGPPREZZO  Dec175    `xml:"http://www.csc.com/stealth3000 MGP_PREZZO,omitempty"`
	MGPDATAINS string    `xml:"http://www.csc.com/stealth3000 MGP_DATA_INS,omitempty"`
	MGPDATAMOD string    `xml:"http://www.csc.com/stealth3000 MGP_DATA_MOD,omitempty"`
	MGPOPERINS string    `xml:"http://www.csc.com/stealth3000 MGP_OPER_INS,omitempty"`
	MGPOPERMOD string    `xml:"http://www.csc.com/stealth3000 MGP_OPER_MOD,omitempty"`
	MGPPRGINS  string    `xml:"http://www.csc.com/stealth3000 MGP_PRG_INS,omitempty"`
	MGPPRGMOD  string    `xml:"http://www.csc.com/stealth3000 MGP_PRG_MOD,omitempty"`
	MGPSOCINS  string    `xml:"http://www.csc.com/stealth3000 MGP_SOC_INS,omitempty"`
}

// XXX
type TBMGPVALASSOC struct {
	MGPGRTCOD  StrMxLn10 `xml:"http://www.csc.com/stealth3000 MGP_GRT_COD,omitempty"`
	MGPTGLCOD  StrMxLn6  `xml:"http://www.csc.com/stealth3000 MGP_TGL_COD,omitempty"`
	MGPPREZZO  Dec175    `xml:"http://www.csc.com/stealth3000 MGP_PREZZO,omitempty"`
	MGPDATAINS string    `xml:"http://www.csc.com/stealth3000 MGP_DATA_INS,omitempty"`
	MGPDATAMOD string    `xml:"http://www.csc.com/stealth3000 MGP_DATA_MOD,omitempty"`
	MGPOPERINS string    `xml:"http://www.csc.com/stealth3000 MGP_OPER_INS,omitempty"`
	MGPOPERMOD string    `xml:"http://www.csc.com/stealth3000 MGP_OPER_MOD,omitempty"`
	MGPPRGINS  string    `xml:"http://www.csc.com/stealth3000 MGP_PRG_INS,omitempty"`
	MGPPRGMOD  string    `xml:"http://www.csc.com/stealth3000 MGP_PRG_MOD,omitempty"`
	MGPSOCINS  string    `xml:"http://www.csc.com/stealth3000 MGP_SOC_INS,omitempty"`
}

// XXX
type TBMGR struct {
	MGRRIGA           int            `xml:"http://www.csc.com/stealth3000 MGR_RIGA,omitempty"`
	MGRTIPOOPER       StrMxLn1       `xml:"http://www.csc.com/stealth3000 MGR_TIPO_OPER,omitempty"`
	MGRTIPOCP         StrMxLn1       `xml:"http://www.csc.com/stealth3000 MGR_TIPO_CP,omitempty"`
	MGRMGACODRIFE     StrMxLn6       `xml:"http://www.csc.com/stealth3000 MGR_MGA_COD_RIFE,omitempty"`
	MGRMGTANNORIFE    int            `xml:"http://www.csc.com/stealth3000 MGR_MGT_ANNO_RIFE,omitempty"`
	MGRMGTINMCODRIFE  StrMxLn3       `xml:"http://www.csc.com/stealth3000 MGR_MGT_INM_COD_RIFE,omitempty"`
	MGRMGTNUMRIFE     int            `xml:"http://www.csc.com/stealth3000 MGR_MGT_NUM_RIFE,omitempty"`
	MGRMGRRIGARIFE    int            `xml:"http://www.csc.com/stealth3000 MGR_MGR_RIGA_RIFE,omitempty"`
	MGRECPCODRIFE     StrMxLn6       `xml:"http://www.csc.com/stealth3000 MGR_ECP_COD_RIFE,omitempty"`
	MGRCPTANNORIFE    int            `xml:"http://www.csc.com/stealth3000 MGR_CPT_ANNO_RIFE,omitempty"`
	MGRCPTNUCPRIFE    int            `xml:"http://www.csc.com/stealth3000 MGR_CPT_NUCP_RIFE,omitempty"`
	MGRCPRRIGARIFE    int            `xml:"http://www.csc.com/stealth3000 MGR_CPR_RIGA_RIFE,omitempty"`
	MGREOFCODRIFE     StrMxLn6       `xml:"http://www.csc.com/stealth3000 MGR_EOF_COD_RIFE,omitempty"`
	MGROFTANNORIFE    int            `xml:"http://www.csc.com/stealth3000 MGR_OFT_ANNO_RIFE,omitempty"`
	MGROFTNUOFRIFE    int            `xml:"http://www.csc.com/stealth3000 MGR_OFT_NUOF_RIFE,omitempty"`
	MGROFRRIGARIFE    int            `xml:"http://www.csc.com/stealth3000 MGR_OFR_RIGA_RIFE,omitempty"`
	MGRSTGANNORIFE    int            `xml:"http://www.csc.com/stealth3000 MGR_STG_ANNO_RIFE,omitempty"`
	MGRSTGCODRIFE     StrMxLn2       `xml:"http://www.csc.com/stealth3000 MGR_STG_COD_RIFE,omitempty"`
	MGRMRCCODRIFE     StrMxLn6       `xml:"http://www.csc.com/stealth3000 MGR_MRC_COD_RIFE,omitempty"`
	MGROCTNUORRIFE    int            `xml:"http://www.csc.com/stealth3000 MGR_OCT_NUOR_RIFE,omitempty"`
	MGROCRRIGARIFE    int            `xml:"http://www.csc.com/stealth3000 MGR_OCR_RIGA_RIFE,omitempty"`
	MGRISTMODCOD      StrMxLn15      `xml:"http://www.csc.com/stealth3000 MGR_IST_MOD_COD,omitempty"`
	MGRISTCMBCOD      StrMxLn1       `xml:"http://www.csc.com/stealth3000 MGR_IST_CMB_COD,omitempty"`
	MGRISTPARCOD      StrMxLn15      `xml:"http://www.csc.com/stealth3000 MGR_IST_PAR_COD,omitempty"`
	MGRISTCOLCOD      StrMxLn5       `xml:"http://www.csc.com/stealth3000 MGR_IST_COL_COD,omitempty"`
	MGRISTMISCOD      StrMxLn5       `xml:"http://www.csc.com/stealth3000 MGR_IST_MIS_COD,omitempty"`
	MGRISTTPVCOD      StrMxLn1       `xml:"http://www.csc.com/stealth3000 MGR_IST_TPV_COD,omitempty"`
	MGRISTVARCOD      StrMxLn10      `xml:"http://www.csc.com/stealth3000 MGR_IST_VAR_COD,omitempty"`
	MGRISTDRPCOD      StrMxLn2       `xml:"http://www.csc.com/stealth3000 MGR_IST_DRP_COD,omitempty"`
	MGRISTSTTCOD      StrMxLn2       `xml:"http://www.csc.com/stealth3000 MGR_IST_STT_COD,omitempty"`
	MGRISTETICOD      StrMxLn6       `xml:"http://www.csc.com/stealth3000 MGR_IST_ETI_COD,omitempty"`
	MGRISTCARCOD      StrMxLn6       `xml:"http://www.csc.com/stealth3000 MGR_IST_CAR_COD,omitempty"`
	MGRISTAVZCOD      StrMxLn2       `xml:"http://www.csc.com/stealth3000 MGR_IST_AVZ_COD,omitempty"`
	MGRISTFASCOD      StrMxLn2       `xml:"http://www.csc.com/stealth3000 MGR_IST_FAS_COD,omitempty"`
	MGRISTOPECOD      StrMxLn6       `xml:"http://www.csc.com/stealth3000 MGR_IST_OPE_COD,omitempty"`
	MGRISTPEZZO       StrMxLn6       `xml:"http://www.csc.com/stealth3000 MGR_IST_PEZZO,omitempty"`
	MGRISTFLGM        StrFlag        `xml:"http://www.csc.com/stealth3000 MGR_IST_F_LGM,omitempty"`
	MGRMGACOD         StrMxLn6       `xml:"http://www.csc.com/stealth3000 MGR_MGA_COD,omitempty"`
	MGRMGUCOD         StrMxLn10      `xml:"http://www.csc.com/stealth3000 MGR_MGU_COD,omitempty"`
	MGRMGUESSCOD      StrMxLn20      `xml:"http://www.csc.com/stealth3000 MGR_MGU_ESS_COD,omitempty"`
	MGRMATCOD         StrMxLn10      `xml:"http://www.csc.com/stealth3000 MGR_MAT_COD,omitempty"`
	MGRFRNCOD         StrMxLn10      `xml:"http://www.csc.com/stealth3000 MGR_FRN_COD,omitempty"`
	MGRCLHCOD         StrMxLn6       `xml:"http://www.csc.com/stealth3000 MGR_CLH_COD,omitempty"`
	MGRSGACOD         StrMxLn6       `xml:"http://www.csc.com/stealth3000 MGR_SGA_COD,omitempty"`
	MGRMADCOD         StrMxLn6       `xml:"http://www.csc.com/stealth3000 MGR_MAD_COD,omitempty"`
	MGRBAGNO          StrMxLn10      `xml:"http://www.csc.com/stealth3000 MGR_BAGNO,omitempty"`
	MGRCELLA          StrMxLn10      `xml:"http://www.csc.com/stealth3000 MGR_CELLA,omitempty"`
	MGRDIVCOD         StrMxLn6       `xml:"http://www.csc.com/stealth3000 MGR_DIV_COD,omitempty"`
	MGRSTGANNO        int            `xml:"http://www.csc.com/stealth3000 MGR_STG_ANNO,omitempty"`
	MGRSTGCOD         StrMxLn2       `xml:"http://www.csc.com/stealth3000 MGR_STG_COD,omitempty"`
	MGRTPPCOD         StrMxLn6       `xml:"http://www.csc.com/stealth3000 MGR_TPP_COD,omitempty"`
	MGRECPCOD         StrMxLn6       `xml:"http://www.csc.com/stealth3000 MGR_ECP_COD,omitempty"`
	MGRCPTANNO        int            `xml:"http://www.csc.com/stealth3000 MGR_CPT_ANNO,omitempty"`
	MGRCPTNUCP        int            `xml:"http://www.csc.com/stealth3000 MGR_CPT_NUCP,omitempty"`
	MGRCPRRIGA        int            `xml:"http://www.csc.com/stealth3000 MGR_CPR_RIGA,omitempty"`
	MGREOFCOD         StrMxLn6       `xml:"http://www.csc.com/stealth3000 MGR_EOF_COD,omitempty"`
	MGROFTANNO        int            `xml:"http://www.csc.com/stealth3000 MGR_OFT_ANNO,omitempty"`
	MGROFTNUOF        int            `xml:"http://www.csc.com/stealth3000 MGR_OFT_NUOF,omitempty"`
	MGROFRRIGA        int            `xml:"http://www.csc.com/stealth3000 MGR_OFR_RIGA,omitempty"`
	MGRUMICOD         StrMxLn3       `xml:"http://www.csc.com/stealth3000 MGR_UMI_COD,omitempty"`
	MGRNUMFATC        int            `xml:"http://www.csc.com/stealth3000 MGR_NUM_FATC,omitempty"`
	MGRDENFATC        int            `xml:"http://www.csc.com/stealth3000 MGR_DEN_FATC,omitempty"`
	MGRGRTCOD         StrMxLn10      `xml:"http://www.csc.com/stealth3000 MGR_GRT_COD,omitempty"`
	MGRLOTCOD         StrMxLn10      `xml:"http://www.csc.com/stealth3000 MGR_LOT_COD,omitempty"`
	MGRQTA            Dec183         `xml:"http://www.csc.com/stealth3000 MGR_QTA,omitempty"`
	MGRQTALOT         int            `xml:"http://www.csc.com/stealth3000 MGR_QTALOT,omitempty"`
	MGRFACCSAL        StrFlag        `xml:"http://www.csc.com/stealth3000 MGR_F_ACCSAL,omitempty"`
	MGRTTCCOD         StrMxLn6       `xml:"http://www.csc.com/stealth3000 MGR_TTC_COD,omitempty"`
	MGRFVALORE        StrFlag        `xml:"http://www.csc.com/stealth3000 MGR_F_VALORE,omitempty"`
	MGRLSTCOD         StrMxLn6       `xml:"http://www.csc.com/stealth3000 MGR_LST_COD,omitempty"`
	MGRDDEC           Date           `xml:"http://www.csc.com/stealth3000 MGR_DDEC,omitempty"`
	MGRPRZ            Dec175         `xml:"http://www.csc.com/stealth3000 MGR_PRZ,omitempty"`
	MGRIVACODALIQ     StrMxLn6       `xml:"http://www.csc.com/stealth3000 MGR_IVA_COD_ALIQ,omitempty"`
	MGRMERCOD         StrMxLn6       `xml:"http://www.csc.com/stealth3000 MGR_MER_COD,omitempty"`
	MGROTCCOD         StrMxLn6       `xml:"http://www.csc.com/stealth3000 MGR_OTC_COD,omitempty"`
	MGRCAVCOD         StrMxLn6       `xml:"http://www.csc.com/stealth3000 MGR_CAV_COD,omitempty"`
	MGRSTGANNOFATT    int            `xml:"http://www.csc.com/stealth3000 MGR_STG_ANNO_FATT,omitempty"`
	MGRSTGCODFATT     StrMxLn2       `xml:"http://www.csc.com/stealth3000 MGR_STG_COD_FATT,omitempty"`
	MGRMRCCOD         StrMxLn6       `xml:"http://www.csc.com/stealth3000 MGR_MRC_COD,omitempty"`
	MGRTIVCOD         StrMxLn6       `xml:"http://www.csc.com/stealth3000 MGR_TIV_COD,omitempty"`
	MGRLNGCOD         StrMxLn3       `xml:"http://www.csc.com/stealth3000 MGR_LNG_COD,omitempty"`
	MGRCPGCOD         StrMxLn6       `xml:"http://www.csc.com/stealth3000 MGR_CPG_COD,omitempty"`
	MGRSFIN           Dec63          `xml:"http://www.csc.com/stealth3000 MGR_SFIN,omitempty"`
	MGRSTES           Dec63          `xml:"http://www.csc.com/stealth3000 MGR_STES,omitempty"`
	MGRIVACODESEN     StrMxLn6       `xml:"http://www.csc.com/stealth3000 MGR_IVA_COD_ESEN,omitempty"`
	MGRNLTI           StrMxLn30      `xml:"http://www.csc.com/stealth3000 MGR_NLTI,omitempty"`
	MGRBNCCOD         StrMxLn20      `xml:"http://www.csc.com/stealth3000 MGR_BNC_COD,omitempty"`
	MGRIBANPREF       StrMxLn4       `xml:"http://www.csc.com/stealth3000 MGR_IBANPREF,omitempty"`
	MGRCC             StrMxLn30      `xml:"http://www.csc.com/stealth3000 MGR_CC,omitempty"`
	MGRCHVAL1         Dec138         `xml:"http://www.csc.com/stealth3000 MGR_CHVAL1,omitempty"`
	MGRCHVAL2         Dec138         `xml:"http://www.csc.com/stealth3000 MGR_CHVAL2,omitempty"`
	MGRFFATT          StrFlag        `xml:"http://www.csc.com/stealth3000 MGR_F_FATT,omitempty"`
	MGRFPTANNORIFE    int            `xml:"http://www.csc.com/stealth3000 MGR_FPT_ANNO_RIFE,omitempty"`
	MGRFPTFRNCODRIFE  StrMxLn10      `xml:"http://www.csc.com/stealth3000 MGR_FPT_FRN_COD_RIFE,omitempty"`
	MGRFPTNUMFRNRIFE  StrMxLn10      `xml:"http://www.csc.com/stealth3000 MGR_FPT_NUM_FRN_RIFE,omitempty"`
	MGRFPRRIGARIFE    int            `xml:"http://www.csc.com/stealth3000 MGR_FPR_RIGA_RIFE,omitempty"`
	MGRTIACOD         StrMxLn6       `xml:"http://www.csc.com/stealth3000 MGR_TIA_COD,omitempty"`
	MGRTPPCODFATT     StrMxLn6       `xml:"http://www.csc.com/stealth3000 MGR_TPP_COD_FATT,omitempty"`
	MGRDIVCODFATT     StrMxLn6       `xml:"http://www.csc.com/stealth3000 MGR_DIV_COD_FATT,omitempty"`
	MGRLINCOD         StrMxLn6       `xml:"http://www.csc.com/stealth3000 MGR_LIN_COD,omitempty"`
	MGRFRNCODFATTAV   StrMxLn10      `xml:"http://www.csc.com/stealth3000 MGR_FRN_COD_FATT_AV,omitempty"`
	MGRMADCODFATT     StrMxLn6       `xml:"http://www.csc.com/stealth3000 MGR_MAD_COD_FATT,omitempty"`
	MGRVLTCOD         StrMxLn4       `xml:"http://www.csc.com/stealth3000 MGR_VLT_COD,omitempty"`
	MGRAVTANNORIFE    int            `xml:"http://www.csc.com/stealth3000 MGR_AVT_ANNO_RIFE,omitempty"`
	MGRAVTNUMRIFE     int            `xml:"http://www.csc.com/stealth3000 MGR_AVT_NUM_RIFE,omitempty"`
	MGRAVLRIGARIFE    int            `xml:"http://www.csc.com/stealth3000 MGR_AVL_RIGA_RIFE,omitempty"`
	MGRRNDIDRIFE      StrMxLn18      `xml:"http://www.csc.com/stealth3000 MGR_RND_ID_RIFE,omitempty"`
	MGRMGRRIGAPADRE   int            `xml:"http://www.csc.com/stealth3000 MGR_MGR_RIGA_PADRE,omitempty"`
	MGRMGACODPROD     StrMxLn6       `xml:"http://www.csc.com/stealth3000 MGR_MGA_COD_PROD,omitempty"`
	MGRMGTANNOPROD    int            `xml:"http://www.csc.com/stealth3000 MGR_MGT_ANNO_PROD,omitempty"`
	MGRMGTINMCODPROD  StrMxLn3       `xml:"http://www.csc.com/stealth3000 MGR_MGT_INM_COD_PROD,omitempty"`
	MGRMGTNUMPROD     int            `xml:"http://www.csc.com/stealth3000 MGR_MGT_NUM_PROD,omitempty"`
	MGRMGRRIGAPROD    int            `xml:"http://www.csc.com/stealth3000 MGR_MGR_RIGA_PROD,omitempty"`
	MGRLPTANNO        int            `xml:"http://www.csc.com/stealth3000 MGR_LPT_ANNO,omitempty"`
	MGRLPTINLCOD      StrMxLn3       `xml:"http://www.csc.com/stealth3000 MGR_LPT_INL_COD,omitempty"`
	MGRLPTNUM         int            `xml:"http://www.csc.com/stealth3000 MGR_LPT_NUM,omitempty"`
	MGRLPRRIGA        int            `xml:"http://www.csc.com/stealth3000 MGR_LPR_RIGA,omitempty"`
	MGRFMATR          StrFlag        `xml:"http://www.csc.com/stealth3000 MGR_F_MATR,omitempty"`
	MGRFDIRINV        StrFlag        `xml:"http://www.csc.com/stealth3000 MGR_F_DIRINV,omitempty"`
	MGRECLCOD         StrMxLn6       `xml:"http://www.csc.com/stealth3000 MGR_ECL_COD,omitempty"`
	MGRCLLANNO        int            `xml:"http://www.csc.com/stealth3000 MGR_CLL_ANNO,omitempty"`
	MGRCLLCOD         int            `xml:"http://www.csc.com/stealth3000 MGR_CLL_COD,omitempty"`
	MGRPBTSOCCOD      StrMxLn3       `xml:"http://www.csc.com/stealth3000 MGR_PBT_SOC_COD,omitempty"`
	MGRPBTANNO        int            `xml:"http://www.csc.com/stealth3000 MGR_PBT_ANNO,omitempty"`
	MGRPBTINPCOD      StrMxLn3       `xml:"http://www.csc.com/stealth3000 MGR_PBT_INP_COD,omitempty"`
	MGRPBTNUM         int            `xml:"http://www.csc.com/stealth3000 MGR_PBT_NUM,omitempty"`
	MGRSASCOD         StrMxLn2       `xml:"http://www.csc.com/stealth3000 MGR_SAS_COD,omitempty"`
	MGRCDBCIPCOD      StrMxLn6       `xml:"http://www.csc.com/stealth3000 MGR_CDB_CIP_COD,omitempty"`
	MGRCFBGRTCOD      StrMxLn10      `xml:"http://www.csc.com/stealth3000 MGR_CFB_GRT_COD,omitempty"`
	MGRCFBFRNCOD      StrMxLn10      `xml:"http://www.csc.com/stealth3000 MGR_CFB_FRN_COD,omitempty"`
	MGRCFBMGACOD      StrMxLn6       `xml:"http://www.csc.com/stealth3000 MGR_CFB_MGA_COD,omitempty"`
	MGRPITANNORIFE    int            `xml:"http://www.csc.com/stealth3000 MGR_PIT_ANNO_RIFE,omitempty"`
	MGRPITCODRIFE     StrMxLn20      `xml:"http://www.csc.com/stealth3000 MGR_PIT_COD_RIFE,omitempty"`
	MGRDATACHIUSPES   Date           `xml:"http://www.csc.com/stealth3000 MGR_DATA_CHIU_SPES,omitempty"`
	MGRFCHIUSPES      StrFlag        `xml:"http://www.csc.com/stealth3000 MGR_F_CHIU_SPES,omitempty"`
	MGRASTSOCINS      StrMxLn3       `xml:"http://www.csc.com/stealth3000 MGR_AST_SOC_INS,omitempty"`
	MGRFFALLATI       StrFlag        `xml:"http://www.csc.com/stealth3000 MGR_F_FALLATI,omitempty"`
	MGRMGACODREVERSE  StrMxLn6       `xml:"http://www.csc.com/stealth3000 MGR_MGA_COD_REVERSE,omitempty"`
	MGRANNOREVERSE    int            `xml:"http://www.csc.com/stealth3000 MGR_ANNO_REVERSE,omitempty"`
	MGRINMCODREVERSE  StrMxLn3       `xml:"http://www.csc.com/stealth3000 MGR_INM_COD_REVERSE,omitempty"`
	MGRNUMREVERSE     int            `xml:"http://www.csc.com/stealth3000 MGR_NUM_REVERSE,omitempty"`
	MGRMGRRIGAREVERSE int            `xml:"http://www.csc.com/stealth3000 MGR_MGR_RIGA_REVERSE,omitempty"`
	MGRLTIANNO        int            `xml:"http://www.csc.com/stealth3000 MGR_LTI_ANNO,omitempty"`
	MGRLTINUM         int            `xml:"http://www.csc.com/stealth3000 MGR_LTI_NUM,omitempty"`
	MGROOTSOCCOD      string         `xml:"http://www.csc.com/stealth3000 MGR_OOT_SOC_COD,omitempty"`
	MGROOTANNO        int            `xml:"http://www.csc.com/stealth3000 MGR_OOT_ANNO,omitempty"`
	MGROOTNUM         int            `xml:"http://www.csc.com/stealth3000 MGR_OOT_NUM,omitempty"`
	MGRMGACODGROUP    StrMxLn6       `xml:"http://www.csc.com/stealth3000 MGR_MGA_COD_GROUP,omitempty"`
	MGRANNOGROUP      int            `xml:"http://www.csc.com/stealth3000 MGR_ANNO_GROUP,omitempty"`
	MGRINMCODGROUP    StrMxLn3       `xml:"http://www.csc.com/stealth3000 MGR_INM_COD_GROUP,omitempty"`
	MGRNUMGROUP       int            `xml:"http://www.csc.com/stealth3000 MGR_NUM_GROUP,omitempty"`
	MGRMGRRIGAGROUP   int            `xml:"http://www.csc.com/stealth3000 MGR_MGR_RIGA_GROUP,omitempty"`
	MGRFPRZIVA        StrFlag        `xml:"http://www.csc.com/stealth3000 MGR_F_PRZIVA,omitempty"`
	MGRSOCCODCMT      string         `xml:"http://www.csc.com/stealth3000 MGR_SOC_COD_CMT,omitempty"`
	MGRSTATOCMT       StrMxLn1       `xml:"http://www.csc.com/stealth3000 MGR_STATO_CMT,omitempty"`
	MGRCIPCODCMT      StrMxLn6       `xml:"http://www.csc.com/stealth3000 MGR_CIP_COD_CMT,omitempty"`
	MGRDATAINS        string         `xml:"http://www.csc.com/stealth3000 MGR_DATA_INS,omitempty"`
	MGRDATAMOD        string         `xml:"http://www.csc.com/stealth3000 MGR_DATA_MOD,omitempty"`
	MGROPERINS        string         `xml:"http://www.csc.com/stealth3000 MGR_OPER_INS,omitempty"`
	MGROPERMOD        string         `xml:"http://www.csc.com/stealth3000 MGR_OPER_MOD,omitempty"`
	MGRPRGINS         string         `xml:"http://www.csc.com/stealth3000 MGR_PRG_INS,omitempty"`
	MGRPRGMOD         string         `xml:"http://www.csc.com/stealth3000 MGR_PRG_MOD,omitempty"`
	MGRSOCINS         string         `xml:"http://www.csc.com/stealth3000 MGR_SOC_INS,omitempty"`
	DATOAGG           []TDATOAGG     `xml:"http://www.csc.com/stealth3000 DATO_AGG,omitempty"`
	DETTBMGRASSOC     DETTBMGRASSOC  `xml:"http://www.csc.com/stealth3000 DETT_BMGR_ASSOC,omitempty"`
	DETTBMGRTGL       DETTBMGRTGL    `xml:"http://www.csc.com/stealth3000 DETT_BMGR_TGL,omitempty"`
	DETTBMGRAGE       DETTBMGRAGE    `xml:"http://www.csc.com/stealth3000 DETT_BMGR_AGE,omitempty"`
	DETTBMGC          DETTBMGC       `xml:"http://www.csc.com/stealth3000 DETT_BMGC,omitempty"`
	DETTBMGP          DETTBMGP       `xml:"http://www.csc.com/stealth3000 DETT_BMGP,omitempty"`
	DETTBMGRGRTFPR    DETTBMGRGRTFPR `xml:"http://www.csc.com/stealth3000 DETT_BMGR_GRT_FPR,omitempty"`
	DETTBMGRNOT       DETTBMGRNOT    `xml:"http://www.csc.com/stealth3000 DETT_BMGR_NOT,omitempty"`
	DETTBMGRBAR       DETTBMGRBAR    `xml:"http://www.csc.com/stealth3000 DETT_BMGR_BAR,omitempty"`
	DETTBMGRCDS       DETTBMGRCDS    `xml:"http://www.csc.com/stealth3000 DETT_BMGR_CDS,omitempty"`
}

// XXX
type TBMGRAGE struct {
	MGRAGEAGECODC  StrMxLn10      `xml:"http://www.csc.com/stealth3000 MGR_AGE_AGE_COD_C,omitempty"`
	MGRAGEAGECODL  StrMxLn10      `xml:"http://www.csc.com/stealth3000 MGR_AGE_AGE_COD_L,omitempty"`
	MGRAGEORD      int            `xml:"http://www.csc.com/stealth3000 MGR_AGE_ORD,omitempty"`
	MGRAGEDATAINS  string         `xml:"http://www.csc.com/stealth3000 MGR_AGE_DATA_INS,omitempty"`
	MGRAGEDATAMOD  string         `xml:"http://www.csc.com/stealth3000 MGR_AGE_DATA_MOD,omitempty"`
	MGRAGEOPERINS  string         `xml:"http://www.csc.com/stealth3000 MGR_AGE_OPER_INS,omitempty"`
	MGRAGEOPERMOD  string         `xml:"http://www.csc.com/stealth3000 MGR_AGE_OPER_MOD,omitempty"`
	MGRAGEPRGINS   string         `xml:"http://www.csc.com/stealth3000 MGR_AGE_PRG_INS,omitempty"`
	MGRAGEPRGMOD   string         `xml:"http://www.csc.com/stealth3000 MGR_AGE_PRG_MOD,omitempty"`
	MGRAGESOCINS   string         `xml:"http://www.csc.com/stealth3000 MGR_AGE_SOC_INS,omitempty"`
	DETTBMGRAGEPRV DETTBMGRAGEPRV `xml:"http://www.csc.com/stealth3000 DETT_BMGR_AGE_PRV,omitempty"`
}

// XXX
type TBMGRAGEPRV struct {
	MGRAGEPRVORD     int    `xml:"http://www.csc.com/stealth3000 MGR_AGE_PRV_ORD,omitempty"`
	MGRAGEPRVPRC     Dec63  `xml:"http://www.csc.com/stealth3000 MGR_AGE_PRV_PRC,omitempty"`
	MGRAGEPRVDATAINS string `xml:"http://www.csc.com/stealth3000 MGR_AGE_PRV_DATA_INS,omitempty"`
	MGRAGEPRVDATAMOD string `xml:"http://www.csc.com/stealth3000 MGR_AGE_PRV_DATA_MOD,omitempty"`
	MGRAGEPRVOPERINS string `xml:"http://www.csc.com/stealth3000 MGR_AGE_PRV_OPER_INS,omitempty"`
	MGRAGEPRVOPERMOD string `xml:"http://www.csc.com/stealth3000 MGR_AGE_PRV_OPER_MOD,omitempty"`
	MGRAGEPRVPRGINS  string `xml:"http://www.csc.com/stealth3000 MGR_AGE_PRV_PRG_INS,omitempty"`
	MGRAGEPRVPRGMOD  string `xml:"http://www.csc.com/stealth3000 MGR_AGE_PRV_PRG_MOD,omitempty"`
	MGRAGEPRVSOCINS  string `xml:"http://www.csc.com/stealth3000 MGR_AGE_PRV_SOC_INS,omitempty"`
}

// XXX
type TBMGRASSOC struct {
	MGRRIGA          int              `xml:"http://www.csc.com/stealth3000 MGR_RIGA,omitempty"`
	MGRMGACOD        StrMxLn6         `xml:"http://www.csc.com/stealth3000 MGR_MGA_COD,omitempty"`
	MGRMGUCOD        StrMxLn10        `xml:"http://www.csc.com/stealth3000 MGR_MGU_COD,omitempty"`
	MGRMGUESSCOD     StrMxLn20        `xml:"http://www.csc.com/stealth3000 MGR_MGU_ESS_COD,omitempty"`
	MGRISTMODCOD     StrMxLn15        `xml:"http://www.csc.com/stealth3000 MGR_IST_MOD_COD,omitempty"`
	MGRISTCMBCOD     StrMxLn1         `xml:"http://www.csc.com/stealth3000 MGR_IST_CMB_COD,omitempty"`
	MGRISTPARCOD     StrMxLn15        `xml:"http://www.csc.com/stealth3000 MGR_IST_PAR_COD,omitempty"`
	MGRISTCOLCOD     StrMxLn5         `xml:"http://www.csc.com/stealth3000 MGR_IST_COL_COD,omitempty"`
	MGRISTMISCOD     StrMxLn5         `xml:"http://www.csc.com/stealth3000 MGR_IST_MIS_COD,omitempty"`
	MGRISTTPVCOD     StrMxLn1         `xml:"http://www.csc.com/stealth3000 MGR_IST_TPV_COD,omitempty"`
	MGRISTVARCOD     StrMxLn10        `xml:"http://www.csc.com/stealth3000 MGR_IST_VAR_COD,omitempty"`
	MGRISTDRPCOD     StrMxLn2         `xml:"http://www.csc.com/stealth3000 MGR_IST_DRP_COD,omitempty"`
	MGRISTSTTCOD     StrMxLn2         `xml:"http://www.csc.com/stealth3000 MGR_IST_STT_COD,omitempty"`
	MGRISTETICOD     StrMxLn6         `xml:"http://www.csc.com/stealth3000 MGR_IST_ETI_COD,omitempty"`
	MGRISTCARCOD     StrMxLn6         `xml:"http://www.csc.com/stealth3000 MGR_IST_CAR_COD,omitempty"`
	MGRISTAVZCOD     StrMxLn2         `xml:"http://www.csc.com/stealth3000 MGR_IST_AVZ_COD,omitempty"`
	MGRISTFASCOD     StrMxLn2         `xml:"http://www.csc.com/stealth3000 MGR_IST_FAS_COD,omitempty"`
	MGRISTOPECOD     StrMxLn6         `xml:"http://www.csc.com/stealth3000 MGR_IST_OPE_COD,omitempty"`
	MGRISTPEZZO      StrMxLn6         `xml:"http://www.csc.com/stealth3000 MGR_IST_PEZZO,omitempty"`
	MGRISTFLGM       StrFlag          `xml:"http://www.csc.com/stealth3000 MGR_IST_F_LGM,omitempty"`
	MGRFRNCOD        StrMxLn10        `xml:"http://www.csc.com/stealth3000 MGR_FRN_COD,omitempty"`
	MGRCLHCOD        StrMxLn6         `xml:"http://www.csc.com/stealth3000 MGR_CLH_COD,omitempty"`
	MGRSGACOD        StrMxLn6         `xml:"http://www.csc.com/stealth3000 MGR_SGA_COD,omitempty"`
	MGRMADCOD        StrMxLn6         `xml:"http://www.csc.com/stealth3000 MGR_MAD_COD,omitempty"`
	MGRBAGNO         StrMxLn10        `xml:"http://www.csc.com/stealth3000 MGR_BAGNO,omitempty"`
	MGRCELLA         StrMxLn10        `xml:"http://www.csc.com/stealth3000 MGR_CELLA,omitempty"`
	MGRDIVCOD        StrMxLn6         `xml:"http://www.csc.com/stealth3000 MGR_DIV_COD,omitempty"`
	MGRSTGANNO       int              `xml:"http://www.csc.com/stealth3000 MGR_STG_ANNO,omitempty"`
	MGRSTGCOD        StrMxLn2         `xml:"http://www.csc.com/stealth3000 MGR_STG_COD,omitempty"`
	MGRTPPCOD        StrMxLn6         `xml:"http://www.csc.com/stealth3000 MGR_TPP_COD,omitempty"`
	MGRCPTECPCOD     StrMxLn6         `xml:"http://www.csc.com/stealth3000 MGR_CPT_ECP_COD,omitempty"`
	MGRCPTANNO       int              `xml:"http://www.csc.com/stealth3000 MGR_CPT_ANNO,omitempty"`
	MGRCPTNUCP       int              `xml:"http://www.csc.com/stealth3000 MGR_CPT_NUCP,omitempty"`
	MGRCPRRIGA       int              `xml:"http://www.csc.com/stealth3000 MGR_CPR_RIGA,omitempty"`
	MGROFTEOFCOD     StrMxLn6         `xml:"http://www.csc.com/stealth3000 MGR_OFT_EOF_COD,omitempty"`
	MGROFTANNO       int              `xml:"http://www.csc.com/stealth3000 MGR_OFT_ANNO,omitempty"`
	MGROFTNUOF       int              `xml:"http://www.csc.com/stealth3000 MGR_OFT_NUOF,omitempty"`
	MGROFRRIGA       int              `xml:"http://www.csc.com/stealth3000 MGR_OFR_RIGA,omitempty"`
	MGRUMICOD        StrMxLn3         `xml:"http://www.csc.com/stealth3000 MGR_UMI_COD,omitempty"`
	MGRNUMFATC       int              `xml:"http://www.csc.com/stealth3000 MGR_NUM_FATC,omitempty"`
	MGRDENFATC       int              `xml:"http://www.csc.com/stealth3000 MGR_DEN_FATC,omitempty"`
	MGRGRTCOD        StrMxLn10        `xml:"http://www.csc.com/stealth3000 MGR_GRT_COD,omitempty"`
	MGRLOTCOD        StrMxLn10        `xml:"http://www.csc.com/stealth3000 MGR_LOT_COD,omitempty"`
	MGRQTA           Dec183           `xml:"http://www.csc.com/stealth3000 MGR_QTA,omitempty"`
	MGRQTALOT        int              `xml:"http://www.csc.com/stealth3000 MGR_QTALOT,omitempty"`
	MGRMATCOD        StrMxLn10        `xml:"http://www.csc.com/stealth3000 MGR_MAT_COD,omitempty"`
	MGRTIPOOPER      StrMxLn1         `xml:"http://www.csc.com/stealth3000 MGR_TIPO_OPER,omitempty"`
	MGRECPCODRIFE    StrMxLn6         `xml:"http://www.csc.com/stealth3000 MGR_ECP_COD_RIFE,omitempty"`
	MGRCPTANNORIFE   int              `xml:"http://www.csc.com/stealth3000 MGR_CPT_ANNO_RIFE,omitempty"`
	MGRCPTNUCPRIFE   int              `xml:"http://www.csc.com/stealth3000 MGR_CPT_NUCP_RIFE,omitempty"`
	MGRCPRRIGARIFE   int              `xml:"http://www.csc.com/stealth3000 MGR_CPR_RIGA_RIFE,omitempty"`
	MGRPRZ           Dec175           `xml:"http://www.csc.com/stealth3000 MGR_PRZ,omitempty"`
	MGRVLTCOD        StrMxLn4         `xml:"http://www.csc.com/stealth3000 MGR_VLT_COD,omitempty"`
	MGRFVALORE       StrFlag          `xml:"http://www.csc.com/stealth3000 MGR_F_VALORE,omitempty"`
	MGRTTCCOD        StrMxLn6         `xml:"http://www.csc.com/stealth3000 MGR_TTC_COD,omitempty"`
	MGRCHVAL1        Dec138           `xml:"http://www.csc.com/stealth3000 MGR_CHVAL1,omitempty"`
	MGRCHVAL2        Dec138           `xml:"http://www.csc.com/stealth3000 MGR_CHVAL2,omitempty"`
	MGRECLCOD        StrMxLn6         `xml:"http://www.csc.com/stealth3000 MGR_ECL_COD,omitempty"`
	MGRCLLANNO       int              `xml:"http://www.csc.com/stealth3000 MGR_CLL_ANNO,omitempty"`
	MGRCLLCOD        int              `xml:"http://www.csc.com/stealth3000 MGR_CLL_COD,omitempty"`
	MGRDATAINS       string           `xml:"http://www.csc.com/stealth3000 MGR_DATA_INS,omitempty"`
	MGRDATAMOD       string           `xml:"http://www.csc.com/stealth3000 MGR_DATA_MOD,omitempty"`
	MGROPERINS       string           `xml:"http://www.csc.com/stealth3000 MGR_OPER_INS,omitempty"`
	MGROPERMOD       string           `xml:"http://www.csc.com/stealth3000 MGR_OPER_MOD,omitempty"`
	MGRPRGINS        string           `xml:"http://www.csc.com/stealth3000 MGR_PRG_INS,omitempty"`
	MGRPRGMOD        string           `xml:"http://www.csc.com/stealth3000 MGR_PRG_MOD,omitempty"`
	MGRSOCINS        string           `xml:"http://www.csc.com/stealth3000 MGR_SOC_INS,omitempty"`
	DATOAGG          []TDATOAGG       `xml:"http://www.csc.com/stealth3000 DATO_AGG,omitempty"`
	DETTBMGRTGLASSOC DETTBMGRTGLASSOC `xml:"http://www.csc.com/stealth3000 DETT_BMGR_TGL_ASSOC,omitempty"`
	DETTBMGPVALASSOC DETTBMGPVALASSOC `xml:"http://www.csc.com/stealth3000 DETT_BMGP_VAL_ASSOC,omitempty"`
	DETTBMGRBARASSOC DETTBMGRBARASSOC `xml:"http://www.csc.com/stealth3000 DETT_BMGR_BAR_ASSOC,omitempty"`
}

// Sizes
type TBMGRBAR struct {
	MGRBARBARCOD         StrMxLn50 `xml:"http://www.csc.com/stealth3000 MGR_BAR_BAR_COD,omitempty"`
	MGRBARTBACOD         StrMxLn6  `xml:"http://www.csc.com/stealth3000 MGR_BAR_TBA_COD,omitempty"`
	MGRBARCLICOD         StrMxLn10 `xml:"http://www.csc.com/stealth3000 MGR_BAR_CLI_COD,omitempty"`
	MGRBARFRNCOD         StrMxLn10 `xml:"http://www.csc.com/stealth3000 MGR_BAR_FRN_COD,omitempty"`
	MGRBARIDENTIFICATIVO StrMxLn50 `xml:"http://www.csc.com/stealth3000 MGR_BAR_IDENTIFICATIVO,omitempty"`
	MGRBARDATAINS        string    `xml:"http://www.csc.com/stealth3000 MGR_BAR_DATA_INS,omitempty"`
	MGRBARDATAMOD        string    `xml:"http://www.csc.com/stealth3000 MGR_BAR_DATA_MOD,omitempty"`
	MGRBAROPERINS        string    `xml:"http://www.csc.com/stealth3000 MGR_BAR_OPER_INS,omitempty"`
	MGRBAROPERMOD        string    `xml:"http://www.csc.com/stealth3000 MGR_BAR_OPER_MOD,omitempty"`
	MGRBARPRGINS         string    `xml:"http://www.csc.com/stealth3000 MGR_BAR_PRG_INS,omitempty"`
	MGRBARPRGMOD         string    `xml:"http://www.csc.com/stealth3000 MGR_BAR_PRG_MOD,omitempty"`
	MGRBARSOCINS         string    `xml:"http://www.csc.com/stealth3000 MGR_BAR_SOC_INS,omitempty"`
}

// XXX
type TBMGRCDS struct {
	MGRCDSCSTCOD      StrMxLn6          `xml:"http://www.csc.com/stealth3000 MGR_CDS_CST_COD,omitempty"`
	MGRCDSQTADISIMPP  Dec183            `xml:"http://www.csc.com/stealth3000 MGR_CDS_QTA_DISIMP_P,omitempty"`
	MGRCDSDATAINS     string            `xml:"http://www.csc.com/stealth3000 MGR_CDS_DATA_INS,omitempty"`
	MGRCDSDATAMOD     string            `xml:"http://www.csc.com/stealth3000 MGR_CDS_DATA_MOD,omitempty"`
	MGRCDSOPERINS     string            `xml:"http://www.csc.com/stealth3000 MGR_CDS_OPER_INS,omitempty"`
	MGRCDSOPERMOD     string            `xml:"http://www.csc.com/stealth3000 MGR_CDS_OPER_MOD,omitempty"`
	MGRCDSPRGINS      string            `xml:"http://www.csc.com/stealth3000 MGR_CDS_PRG_INS,omitempty"`
	MGRCDSPRGMOD      string            `xml:"http://www.csc.com/stealth3000 MGR_CDS_PRG_MOD,omitempty"`
	MGRCDSSOCINS      string            `xml:"http://www.csc.com/stealth3000 MGR_CDS_SOC_INS,omitempty"`
	DETTBMGRCDSCPRTGL DETTBMGRCDSCPRTGL `xml:"http://www.csc.com/stealth3000 DETT_BMGR_CDS_CPR_TGL,omitempty"`
}

// Sizes
type TBMGRCDSCPRTGL struct {
	MGRCDSCPRTGLGRTCODP    StrMxLn10 `xml:"http://www.csc.com/stealth3000 MGR_CDS_CPR_TGL_GRT_COD_P,omitempty"`
	MGRCDSCPRTGLTGLCODP    StrMxLn5  `xml:"http://www.csc.com/stealth3000 MGR_CDS_CPR_TGL_TGL_COD_P,omitempty"`
	MGRCDSCPRTGLQTADISIMPP Dec183    `xml:"http://www.csc.com/stealth3000 MGR_CDS_CPR_TGL_QTA_DISIMP_P,omitempty"`
	MGRCDSCPRTGLDATAINS    string    `xml:"http://www.csc.com/stealth3000 MGR_CDS_CPR_TGL_DATA_INS,omitempty"`
	MGRCDSCPRTGLDATAMOD    string    `xml:"http://www.csc.com/stealth3000 MGR_CDS_CPR_TGL_DATA_MOD,omitempty"`
	MGRCDSCPRTGLOPERINS    string    `xml:"http://www.csc.com/stealth3000 MGR_CDS_CPR_TGL_OPER_INS,omitempty"`
	MGRCDSCPRTGLOPERMOD    string    `xml:"http://www.csc.com/stealth3000 MGR_CDS_CPR_TGL_OPER_MOD,omitempty"`
	MGRCDSCPRTGLPRGINS     string    `xml:"http://www.csc.com/stealth3000 MGR_CDS_CPR_TGL_PRG_INS,omitempty"`
	MGRCDSCPRTGLPRGMOD     string    `xml:"http://www.csc.com/stealth3000 MGR_CDS_CPR_TGL_PRG_MOD,omitempty"`
	MGRCDSCPRTGLSOCINS     string    `xml:"http://www.csc.com/stealth3000 MGR_CDS_CPR_TGL_SOC_INS,omitempty"`
}

// XXX
type TBMGRGRTFPR struct {
	MGRGRTFPRGRTCOD    StrMxLn10 `xml:"http://www.csc.com/stealth3000 MGR_GRT_FPR_GRT_COD,omitempty"`
	MGRGRTFPRGRTFPRCOD int       `xml:"http://www.csc.com/stealth3000 MGR_GRT_FPR_GRT_FPR_COD,omitempty"`
	MGRGRTFPRPRZFPR    Dec175    `xml:"http://www.csc.com/stealth3000 MGR_GRT_FPR_PRZFPR,omitempty"`
	MGRGRTFPRDATAINS   string    `xml:"http://www.csc.com/stealth3000 MGR_GRT_FPR_DATA_INS,omitempty"`
	MGRGRTFPRDATAMOD   string    `xml:"http://www.csc.com/stealth3000 MGR_GRT_FPR_DATA_MOD,omitempty"`
	MGRGRTFPROPERINS   string    `xml:"http://www.csc.com/stealth3000 MGR_GRT_FPR_OPER_INS,omitempty"`
	MGRGRTFPROPERMOD   string    `xml:"http://www.csc.com/stealth3000 MGR_GRT_FPR_OPER_MOD,omitempty"`
	MGRGRTFPRPRGINS    string    `xml:"http://www.csc.com/stealth3000 MGR_GRT_FPR_PRG_INS,omitempty"`
	MGRGRTFPRPRGMOD    string    `xml:"http://www.csc.com/stealth3000 MGR_GRT_FPR_PRG_MOD,omitempty"`
	MGRGRTFPRSOCINS    string    `xml:"http://www.csc.com/stealth3000 MGR_GRT_FPR_SOC_INS,omitempty"`
}

// Sizes
type TBMGRTGL struct {
	MGRTGLGRTCOD  StrMxLn10 `xml:"http://www.csc.com/stealth3000 MGR_TGL_GRT_COD,omitempty"`
	MGRTGLTGLCOD  StrMxLn5  `xml:"http://www.csc.com/stealth3000 MGR_TGL_TGL_COD,omitempty"`
	MGRTGLQTA     int       `xml:"http://www.csc.com/stealth3000 MGR_TGL_QTA,omitempty"`
	MGRTGLDATAINS string    `xml:"http://www.csc.com/stealth3000 MGR_TGL_DATA_INS,omitempty"`
	MGRTGLDATAMOD string    `xml:"http://www.csc.com/stealth3000 MGR_TGL_DATA_MOD,omitempty"`
	MGRTGLOPERINS string    `xml:"http://www.csc.com/stealth3000 MGR_TGL_OPER_INS,omitempty"`
	MGRTGLOPERMOD string    `xml:"http://www.csc.com/stealth3000 MGR_TGL_OPER_MOD,omitempty"`
	MGRTGLPRGINS  string    `xml:"http://www.csc.com/stealth3000 MGR_TGL_PRG_INS,omitempty"`
	MGRTGLPRGMOD  string    `xml:"http://www.csc.com/stealth3000 MGR_TGL_PRG_MOD,omitempty"`
	MGRTGLSOCINS  string    `xml:"http://www.csc.com/stealth3000 MGR_TGL_SOC_INS,omitempty"`
}

// Sizes
type TBMGRTGLASSOC struct {
	MGRTGLGRTCOD  StrMxLn10 `xml:"http://www.csc.com/stealth3000 MGR_TGL_GRT_COD,omitempty"`
	MGRTGLTGLCOD  StrMxLn5  `xml:"http://www.csc.com/stealth3000 MGR_TGL_TGL_COD,omitempty"`
	MGRTGLQTA     int       `xml:"http://www.csc.com/stealth3000 MGR_TGL_QTA,omitempty"`
	MGRTGLDATAINS string    `xml:"http://www.csc.com/stealth3000 MGR_TGL_DATA_INS,omitempty"`
	MGRTGLDATAMOD string    `xml:"http://www.csc.com/stealth3000 MGR_TGL_DATA_MOD,omitempty"`
	MGRTGLOPERINS string    `xml:"http://www.csc.com/stealth3000 MGR_TGL_OPER_INS,omitempty"`
	MGRTGLOPERMOD string    `xml:"http://www.csc.com/stealth3000 MGR_TGL_OPER_MOD,omitempty"`
	MGRTGLPRGINS  string    `xml:"http://www.csc.com/stealth3000 MGR_TGL_PRG_INS,omitempty"`
	MGRTGLPRGMOD  string    `xml:"http://www.csc.com/stealth3000 MGR_TGL_PRG_MOD,omitempty"`
	MGRTGLSOCINS  string    `xml:"http://www.csc.com/stealth3000 MGR_TGL_SOC_INS,omitempty"`
}

// Warehouse Movement
type TBMGT struct {
	MGTSOCCOD        string        `xml:"http://www.csc.com/stealth3000 MGT_SOC_COD,omitempty"`
	MGTMGACOD        StrMxLn6      `xml:"http://www.csc.com/stealth3000 MGT_MGA_COD,omitempty"`
	MGTANNO          int           `xml:"http://www.csc.com/stealth3000 MGT_ANNO,omitempty"`
	MGTINMCOD        StrMxLn3      `xml:"http://www.csc.com/stealth3000 MGT_INM_COD,omitempty"`
	MGTNUM           int           `xml:"http://www.csc.com/stealth3000 MGT_NUM,omitempty"`
	MGTDATADOC       Date          `xml:"http://www.csc.com/stealth3000 MGT_DATA_DOC,omitempty"`
	MGTDATACOMP      Date          `xml:"http://www.csc.com/stealth3000 MGT_DATA_COMP,omitempty"`
	MGTCAMCOD        StrMxLn6      `xml:"http://www.csc.com/stealth3000 MGT_CAM_COD,omitempty"`
	MGTTIPOINTES     StrMxLn1      `xml:"http://www.csc.com/stealth3000 MGT_TIPO_INTES,omitempty"`
	MGTFRNCODINTES   StrMxLn10     `xml:"http://www.csc.com/stealth3000 MGT_FRN_COD_INTES,omitempty"`
	MGTCLICODINTES   StrMxLn10     `xml:"http://www.csc.com/stealth3000 MGT_CLI_COD_INTES,omitempty"`
	MGTMGACODINTES   StrMxLn6      `xml:"http://www.csc.com/stealth3000 MGT_MGA_COD_INTES,omitempty"`
	MGTTIPOSTAMPA    StrMxLn1      `xml:"http://www.csc.com/stealth3000 MGT_TIPO_STAMPA,omitempty"`
	MGTNUMDOCRIF     StrMxLn30     `xml:"http://www.csc.com/stealth3000 MGT_NUM_DOC_RIF,omitempty"`
	MGTDATADOCRIF    Date          `xml:"http://www.csc.com/stealth3000 MGT_DATA_DOC_RIF,omitempty"`
	MGTLNGCOD        StrMxLn3      `xml:"http://www.csc.com/stealth3000 MGT_LNG_COD,omitempty"`
	MGTMGACODDEST    StrMxLn6      `xml:"http://www.csc.com/stealth3000 MGT_MGA_COD_DEST,omitempty"`
	MGTTIPODEST      StrMxLn1      `xml:"http://www.csc.com/stealth3000 MGT_TIPO_DEST,omitempty"`
	MGTCLICODSPED    StrMxLn10     `xml:"http://www.csc.com/stealth3000 MGT_CLI_COD_SPED,omitempty"`
	MGTFRNCODSPED    StrMxLn10     `xml:"http://www.csc.com/stealth3000 MGT_FRN_COD_SPED,omitempty"`
	MGTMGACODSPED    StrMxLn6      `xml:"http://www.csc.com/stealth3000 MGT_MGA_COD_SPED,omitempty"`
	MGTSOGCOD        StrMxLn10     `xml:"http://www.csc.com/stealth3000 MGT_SOG_COD,omitempty"`
	MGTSOICOD        StrMxLn6      `xml:"http://www.csc.com/stealth3000 MGT_SOI_COD,omitempty"`
	MGTRAGSOC        StrMxLn100    `xml:"http://www.csc.com/stealth3000 MGT_RAG_SOC,omitempty"`
	MGTIND           StrMxLn100    `xml:"http://www.csc.com/stealth3000 MGT_IND,omitempty"`
	MGTINT           StrMxLn100    `xml:"http://www.csc.com/stealth3000 MGT_INT,omitempty"`
	MGTCAP           StrMxLn12     `xml:"http://www.csc.com/stealth3000 MGT_CAP,omitempty"`
	MGTLOC           StrMxLn100    `xml:"http://www.csc.com/stealth3000 MGT_LOC,omitempty"`
	MGTSTACOD        StrMxLn3      `xml:"http://www.csc.com/stealth3000 MGT_STA_COD,omitempty"`
	MGTPVRCOD        StrMxLn10     `xml:"http://www.csc.com/stealth3000 MGT_PVR_COD,omitempty"`
	MGTCTRCOD        StrMxLn6      `xml:"http://www.csc.com/stealth3000 MGT_CTR_COD,omitempty"`
	MGTCIMCOD        StrMxLn6      `xml:"http://www.csc.com/stealth3000 MGT_CIM_COD,omitempty"`
	MGTMSPCOD        StrMxLn6      `xml:"http://www.csc.com/stealth3000 MGT_MSP_COD,omitempty"`
	MGTRESCOD        StrMxLn6      `xml:"http://www.csc.com/stealth3000 MGT_RES_COD,omitempty"`
	MGTUMICODPESO    StrMxLn3      `xml:"http://www.csc.com/stealth3000 MGT_UMI_COD_PESO,omitempty"`
	MGTPESONETTO     Dec183        `xml:"http://www.csc.com/stealth3000 MGT_PESO_NETTO,omitempty"`
	MGTPESOLORDO     Dec183        `xml:"http://www.csc.com/stealth3000 MGT_PESO_LORDO,omitempty"`
	MGTUMICODVOLU    StrMxLn3      `xml:"http://www.csc.com/stealth3000 MGT_UMI_COD_VOLU,omitempty"`
	MGTVOLUME        Dec183        `xml:"http://www.csc.com/stealth3000 MGT_VOLUME,omitempty"`
	MGTNCOLLI        int           `xml:"http://www.csc.com/stealth3000 MGT_NCOLLI,omitempty"`
	MGTASPETTO       StrMxLn100    `xml:"http://www.csc.com/stealth3000 MGT_ASPETTO,omitempty"`
	MGTINITRASP      Date          `xml:"http://www.csc.com/stealth3000 MGT_INI_TRASP,omitempty"`
	MGTTRASP         StrMxLn1      `xml:"http://www.csc.com/stealth3000 MGT_TRASP,omitempty"`
	MGTEBRCOD        StrMxLn6      `xml:"http://www.csc.com/stealth3000 MGT_EBR_COD,omitempty"`
	MGTBRXANNO       int           `xml:"http://www.csc.com/stealth3000 MGT_BRX_ANNO,omitempty"`
	MGTBRXNUM        int           `xml:"http://www.csc.com/stealth3000 MGT_BRX_NUM,omitempty"`
	MGTCLICODFATT    StrMxLn10     `xml:"http://www.csc.com/stealth3000 MGT_CLI_COD_FATT,omitempty"`
	MGTCLICODPAGA    StrMxLn10     `xml:"http://www.csc.com/stealth3000 MGT_CLI_COD_PAGA,omitempty"`
	MGTCLIALIASPAGA  StrMxLn20     `xml:"http://www.csc.com/stealth3000 MGT_CLI_ALIAS_PAGA,omitempty"`
	MGTVLTCOD        StrMxLn4      `xml:"http://www.csc.com/stealth3000 MGT_VLT_COD,omitempty"`
	MGTFATCHVAL1     Dec138        `xml:"http://www.csc.com/stealth3000 MGT_FAT_CHVAL1,omitempty"`
	MGTFATCHVAL2     Dec138        `xml:"http://www.csc.com/stealth3000 MGT_FAT_CHVAL2,omitempty"`
	MGTFATANNO       int           `xml:"http://www.csc.com/stealth3000 MGT_FAT_ANNO,omitempty"`
	MGTINFCOD        StrMxLn3      `xml:"http://www.csc.com/stealth3000 MGT_INF_COD,omitempty"`
	MGTFATNUM        int           `xml:"http://www.csc.com/stealth3000 MGT_FAT_NUM,omitempty"`
	MGTFATDATA       Date          `xml:"http://www.csc.com/stealth3000 MGT_FAT_DATA,omitempty"`
	MGTFATDATC       Date          `xml:"http://www.csc.com/stealth3000 MGT_FAT_DATC,omitempty"`
	MGTCAFCOD        StrMxLn6      `xml:"http://www.csc.com/stealth3000 MGT_CAF_COD,omitempty"`
	MGTFATTDOC       StrMxLn1      `xml:"http://www.csc.com/stealth3000 MGT_FAT_TDOC,omitempty"`
	MGTFATTIPOOPER   StrMxLn1      `xml:"http://www.csc.com/stealth3000 MGT_FAT_TIPO_OPER,omitempty"`
	MGTSTGANNO       int           `xml:"http://www.csc.com/stealth3000 MGT_STG_ANNO,omitempty"`
	MGTSTGCOD        StrMxLn2      `xml:"http://www.csc.com/stealth3000 MGT_STG_COD,omitempty"`
	MGTMRCCOD        StrMxLn6      `xml:"http://www.csc.com/stealth3000 MGT_MRC_COD,omitempty"`
	MGTTIVCOD        StrMxLn6      `xml:"http://www.csc.com/stealth3000 MGT_TIV_COD,omitempty"`
	MGTLNGCODFATT    StrMxLn3      `xml:"http://www.csc.com/stealth3000 MGT_LNG_COD_FATT,omitempty"`
	MGTCPGCOD        StrMxLn6      `xml:"http://www.csc.com/stealth3000 MGT_CPG_COD,omitempty"`
	MGTFATSFIN       Dec63         `xml:"http://www.csc.com/stealth3000 MGT_FAT_SFIN,omitempty"`
	MGTFATSTES       Dec63         `xml:"http://www.csc.com/stealth3000 MGT_FAT_STES,omitempty"`
	MGTBNCCOD        StrMxLn20     `xml:"http://www.csc.com/stealth3000 MGT_BNC_COD,omitempty"`
	MGTFATIBANPREF   StrMxLn4      `xml:"http://www.csc.com/stealth3000 MGT_FAT_IBANPREF,omitempty"`
	MGTFATCC         StrMxLn30     `xml:"http://www.csc.com/stealth3000 MGT_FAT_CC,omitempty"`
	MGTIVACODESEN    StrMxLn6      `xml:"http://www.csc.com/stealth3000 MGT_IVA_COD_ESEN,omitempty"`
	MGTFATNLTI       StrMxLn30     `xml:"http://www.csc.com/stealth3000 MGT_FAT_NLTI,omitempty"`
	MGTLTCANNO       int           `xml:"http://www.csc.com/stealth3000 MGT_LTC_ANNO,omitempty"`
	MGTLTCNUM        int           `xml:"http://www.csc.com/stealth3000 MGT_LTC_NUM,omitempty"`
	MGTFATCONT       StrMxLn1      `xml:"http://www.csc.com/stealth3000 MGT_FAT_CONT,omitempty"`
	MGTFRNCODFATT    StrMxLn10     `xml:"http://www.csc.com/stealth3000 MGT_FRN_COD_FATT,omitempty"`
	MGTLNCID         StrMxLn20     `xml:"http://www.csc.com/stealth3000 MGT_LNC_ID,omitempty"`
	MGTTIPDOCASSOC   StrMxLn1      `xml:"http://www.csc.com/stealth3000 MGT_TIP_DOC_ASSOC,omitempty"`
	MGTTIPFATT       StrMxLn1      `xml:"http://www.csc.com/stealth3000 MGT_TIP_FATT,omitempty"`
	MGTMGTMGACODIC   StrMxLn6      `xml:"http://www.csc.com/stealth3000 MGT_MGT_MGA_COD_IC,omitempty"`
	MGTMGTANNOIC     int           `xml:"http://www.csc.com/stealth3000 MGT_MGT_ANNO_IC,omitempty"`
	MGTMGTINMCODIC   StrMxLn3      `xml:"http://www.csc.com/stealth3000 MGT_MGT_INM_COD_IC,omitempty"`
	MGTMGTNUMIC      int           `xml:"http://www.csc.com/stealth3000 MGT_MGT_NUM_IC,omitempty"`
	MGTFIC           StrFlag       `xml:"http://www.csc.com/stealth3000 MGT_F_IC,omitempty"`
	MGTFSTAMPA       StrFlag       `xml:"http://www.csc.com/stealth3000 MGT_F_STAMPA,omitempty"`
	MGTFTIPOLLGM     StrFlag       `xml:"http://www.csc.com/stealth3000 MGT_F_TIPOL_LGM,omitempty"`
	MGTSTATOLGM      StrMxLn1      `xml:"http://www.csc.com/stealth3000 MGT_STATO_LGM,omitempty"`
	MGTMGACODGROUP   StrMxLn6      `xml:"http://www.csc.com/stealth3000 MGT_MGA_COD_GROUP,omitempty"`
	MGTANNOGROUP     int           `xml:"http://www.csc.com/stealth3000 MGT_ANNO_GROUP,omitempty"`
	MGTINMCODGROUP   StrMxLn3      `xml:"http://www.csc.com/stealth3000 MGT_INM_COD_GROUP,omitempty"`
	MGTNUMGROUP      int           `xml:"http://www.csc.com/stealth3000 MGT_NUM_GROUP,omitempty"`
	MGTLMTSOCCOD     string        `xml:"http://www.csc.com/stealth3000 MGT_LMT_SOC_COD,omitempty"`
	MGTLMTNEGCOD     StrMxLn10     `xml:"http://www.csc.com/stealth3000 MGT_LMT_NEG_COD,omitempty"`
	MGTLMTANNO       int           `xml:"http://www.csc.com/stealth3000 MGT_LMT_ANNO,omitempty"`
	MGTLMTNUMP       int           `xml:"http://www.csc.com/stealth3000 MGT_LMT_NUMP,omitempty"`
	MGTLMTKEYLGM     StrMxLn50     `xml:"http://www.csc.com/stealth3000 MGT_LMT_KEY_LGM,omitempty"`
	MGTMGACODREVERSE StrMxLn6      `xml:"http://www.csc.com/stealth3000 MGT_MGA_COD_REVERSE,omitempty"`
	MGTANNOREVERSE   int           `xml:"http://www.csc.com/stealth3000 MGT_ANNO_REVERSE,omitempty"`
	MGTINMCODREVERSE StrMxLn3      `xml:"http://www.csc.com/stealth3000 MGT_INM_COD_REVERSE,omitempty"`
	MGTNUMREVERSE    int           `xml:"http://www.csc.com/stealth3000 MGT_NUM_REVERSE,omitempty"`
	MGTLTIANNO       int           `xml:"http://www.csc.com/stealth3000 MGT_LTI_ANNO,omitempty"`
	MGTLTINUM        int           `xml:"http://www.csc.com/stealth3000 MGT_LTI_NUM,omitempty"`
	MGTCONCODINTO    StrMxLn30     `xml:"http://www.csc.com/stealth3000 MGT_CON_COD_INTO,omitempty"`
	MGTCONCODSPED    StrMxLn30     `xml:"http://www.csc.com/stealth3000 MGT_CON_COD_SPED,omitempty"`
	MGTCONCODFATT    StrMxLn30     `xml:"http://www.csc.com/stealth3000 MGT_CON_COD_FATT,omitempty"`
	MGTTMLCOD        StrMxLn10     `xml:"http://www.csc.com/stealth3000 MGT_TML_COD,omitempty"`
	MGTTIPOMEM       StrMxLn1      `xml:"http://www.csc.com/stealth3000 MGT_TIPO_MEM,omitempty"`
	MGTTIPOMIV       StrMxLn1      `xml:"http://www.csc.com/stealth3000 MGT_TIPO_MIV,omitempty"`
	MGTMEMFQUAD      StrMxLn1      `xml:"http://www.csc.com/stealth3000 MGT_MEM_F_QUAD,omitempty"`
	MGTCAUSWMSCOD    StrMxLn30     `xml:"http://www.csc.com/stealth3000 MGT_CAUS_WMS_COD,omitempty"`
	MGTOOTSOCCOD     string        `xml:"http://www.csc.com/stealth3000 MGT_OOT_SOC_COD,omitempty"`
	MGTOOTANNO       int           `xml:"http://www.csc.com/stealth3000 MGT_OOT_ANNO,omitempty"`
	MGTOOTNUM        int           `xml:"http://www.csc.com/stealth3000 MGT_OOT_NUM,omitempty"`
	MGTFELET         StrMxLn1      `xml:"http://www.csc.com/stealth3000 MGT_F_ELET,omitempty"`
	MGTFART73        StrMxLn1      `xml:"http://www.csc.com/stealth3000 MGT_F_ART73,omitempty"`
	MGTDATAINS       string        `xml:"http://www.csc.com/stealth3000 MGT_DATA_INS,omitempty"`
	MGTDATAMOD       string        `xml:"http://www.csc.com/stealth3000 MGT_DATA_MOD,omitempty"`
	MGTOPERINS       string        `xml:"http://www.csc.com/stealth3000 MGT_OPER_INS,omitempty"`
	MGTOPERMOD       string        `xml:"http://www.csc.com/stealth3000 MGT_OPER_MOD,omitempty"`
	MGTPRGINS        string        `xml:"http://www.csc.com/stealth3000 MGT_PRG_INS,omitempty"`
	MGTPRGMOD        string        `xml:"http://www.csc.com/stealth3000 MGT_PRG_MOD,omitempty"`
	MGTSOCINS        string        `xml:"http://www.csc.com/stealth3000 MGT_SOC_INS,omitempty"`
	DATOAGG          []TDATOAGG    `xml:"http://www.csc.com/stealth3000 DATO_AGG,omitempty"`
	DETTBMGTASSOC    DETTBMGTASSOC `xml:"http://www.csc.com/stealth3000 DETT_BMGT_ASSOC,omitempty"`
	DETTBMGTLNI      DETTBMGTLNI   `xml:"http://www.csc.com/stealth3000 DETT_BMGT_LNI,omitempty"`
	DETTBMGTSPE      DETTBMGTSPE   `xml:"http://www.csc.com/stealth3000 DETT_BMGT_SPE,omitempty"`
	DETTBMGR         DETTBMGR      `xml:"http://www.csc.com/stealth3000 DETT_BMGR,omitempty"`
	DETTBMGTNOT      DETTBMGTNOT   `xml:"http://www.csc.com/stealth3000 DETT_BMGT_NOT,omitempty"`
}

// XXX
type TBMGTASSOC struct {
	MGTSOCCOD      string     `xml:"http://www.csc.com/stealth3000 MGT_SOC_COD,omitempty"`
	MGTMGACOD      StrMxLn6   `xml:"http://www.csc.com/stealth3000 MGT_MGA_COD,omitempty"`
	MGTANNO        int        `xml:"http://www.csc.com/stealth3000 MGT_ANNO,omitempty"`
	MGTINMCOD      StrMxLn3   `xml:"http://www.csc.com/stealth3000 MGT_INM_COD,omitempty"`
	MGTNUM         int        `xml:"http://www.csc.com/stealth3000 MGT_NUM,omitempty"`
	MGTDATADOC     Date       `xml:"http://www.csc.com/stealth3000 MGT_DATA_DOC,omitempty"`
	MGTDATACOMP    Date       `xml:"http://www.csc.com/stealth3000 MGT_DATA_COMP,omitempty"`
	MGTCAMCOD      StrMxLn6   `xml:"http://www.csc.com/stealth3000 MGT_CAM_COD,omitempty"`
	MGTNUMDOCRIF   StrMxLn30  `xml:"http://www.csc.com/stealth3000 MGT_NUM_DOC_RIF,omitempty"`
	MGTDATADOCRIF  Date       `xml:"http://www.csc.com/stealth3000 MGT_DATA_DOC_RIF,omitempty"`
	MGTTIPOINTES   StrMxLn1   `xml:"http://www.csc.com/stealth3000 MGT_TIPO_INTES,omitempty"`
	MGTMGACODINTES StrMxLn6   `xml:"http://www.csc.com/stealth3000 MGT_MGA_COD_INTES,omitempty"`
	MGTLNGCOD      StrMxLn3   `xml:"http://www.csc.com/stealth3000 MGT_LNG_COD,omitempty"`
	MGTTIPDOCASSOC StrMxLn1   `xml:"http://www.csc.com/stealth3000 MGT_TIP_DOC_ASSOC,omitempty"`
	MGTFSTAMPA     StrFlag    `xml:"http://www.csc.com/stealth3000 MGT_F_STAMPA,omitempty"`
	MGTMGACODGROUP StrMxLn6   `xml:"http://www.csc.com/stealth3000 MGT_MGA_COD_GROUP,omitempty"`
	MGTANNOGROUP   int        `xml:"http://www.csc.com/stealth3000 MGT_ANNO_GROUP,omitempty"`
	MGTINMCODGROUP StrMxLn3   `xml:"http://www.csc.com/stealth3000 MGT_INM_COD_GROUP,omitempty"`
	MGTNUMGROUP    int        `xml:"http://www.csc.com/stealth3000 MGT_NUM_GROUP,omitempty"`
	MGTDATAINS     string     `xml:"http://www.csc.com/stealth3000 MGT_DATA_INS,omitempty"`
	MGTDATAMOD     string     `xml:"http://www.csc.com/stealth3000 MGT_DATA_MOD,omitempty"`
	MGTOPERINS     string     `xml:"http://www.csc.com/stealth3000 MGT_OPER_INS,omitempty"`
	MGTOPERMOD     string     `xml:"http://www.csc.com/stealth3000 MGT_OPER_MOD,omitempty"`
	MGTPRGINS      string     `xml:"http://www.csc.com/stealth3000 MGT_PRG_INS,omitempty"`
	MGTPRGMOD      string     `xml:"http://www.csc.com/stealth3000 MGT_PRG_MOD,omitempty"`
	MGTSOCINS      string     `xml:"http://www.csc.com/stealth3000 MGT_SOC_INS,omitempty"`
	DATOAGG        []TDATOAGG `xml:"http://www.csc.com/stealth3000 DATO_AGG,omitempty"`
}

// XXX
type TBMGTLNI struct {
	MGTLNILNGCOD  StrMxLn3   `xml:"http://www.csc.com/stealth3000 MGT_LNI_LNG_COD,omitempty"`
	MGTLNIRAGSOC  StrMxLn100 `xml:"http://www.csc.com/stealth3000 MGT_LNI_RAG_SOC,omitempty"`
	MGTLNIIND     StrMxLn100 `xml:"http://www.csc.com/stealth3000 MGT_LNI_IND,omitempty"`
	MGTLNIINT     StrMxLn100 `xml:"http://www.csc.com/stealth3000 MGT_LNI_INT,omitempty"`
	MGTLNILOC     StrMxLn100 `xml:"http://www.csc.com/stealth3000 MGT_LNI_LOC,omitempty"`
	MGTLNIDATAINS string     `xml:"http://www.csc.com/stealth3000 MGT_LNI_DATA_INS,omitempty"`
	MGTLNIDATAMOD string     `xml:"http://www.csc.com/stealth3000 MGT_LNI_DATA_MOD,omitempty"`
	MGTLNIOPERINS string     `xml:"http://www.csc.com/stealth3000 MGT_LNI_OPER_INS,omitempty"`
	MGTLNIOPERMOD string     `xml:"http://www.csc.com/stealth3000 MGT_LNI_OPER_MOD,omitempty"`
	MGTLNIPRGINS  string     `xml:"http://www.csc.com/stealth3000 MGT_LNI_PRG_INS,omitempty"`
	MGTLNIPRGMOD  string     `xml:"http://www.csc.com/stealth3000 MGT_LNI_PRG_MOD,omitempty"`
	MGTLNISOCINS  string     `xml:"http://www.csc.com/stealth3000 MGT_LNI_SOC_INS,omitempty"`
}

// XXX
type TBMGTSPE struct {
	MGTSPESPECOD  StrMxLn6 `xml:"http://www.csc.com/stealth3000 MGT_SPE_SPE_COD,omitempty"`
	MGTSPEORD     int      `xml:"http://www.csc.com/stealth3000 MGT_SPE_ORD,omitempty"`
	MGTSPEDATAINS string   `xml:"http://www.csc.com/stealth3000 MGT_SPE_DATA_INS,omitempty"`
	MGTSPEDATAMOD string   `xml:"http://www.csc.com/stealth3000 MGT_SPE_DATA_MOD,omitempty"`
	MGTSPEOPERINS string   `xml:"http://www.csc.com/stealth3000 MGT_SPE_OPER_INS,omitempty"`
	MGTSPEOPERMOD string   `xml:"http://www.csc.com/stealth3000 MGT_SPE_OPER_MOD,omitempty"`
	MGTSPEPRGINS  string   `xml:"http://www.csc.com/stealth3000 MGT_SPE_PRG_INS,omitempty"`
	MGTSPEPRGMOD  string   `xml:"http://www.csc.com/stealth3000 MGT_SPE_PRG_MOD,omitempty"`
	MGTSPESOCINS  string   `xml:"http://www.csc.com/stealth3000 MGT_SPE_SOC_INS,omitempty"`
}

// Additional Data
type TDATOAGG struct {
	CAR     string `xml:"http://www.csc.com/stealth3000 CAR,omitempty"`
	DAT     Date   `xml:"http://www.csc.com/stealth3000 DAT,omitempty"`
	NUM     Dec    `xml:"http://www.csc.com/stealth3000 NUM,omitempty"`
	NUMDAGG int    `xml:"NUM_DAGG,attr"`
}

// Translated Description
type TDESLNG struct {
	LNGCOD  StrMxLn3   `xml:"http://www.csc.com/stealth3000 LNG_COD"`
	DES     StrMxLn100 `xml:"http://www.csc.com/stealth3000 DES"`
	DATAINS DateTime   `xml:"http://www.csc.com/stealth3000 DATA_INS,omitempty"`
	DATAMOD DateTime   `xml:"http://www.csc.com/stealth3000 DATA_MOD,omitempty"`
	OPERINS StrMxLn30  `xml:"http://www.csc.com/stealth3000 OPER_INS,omitempty"`
	OPERMOD StrMxLn30  `xml:"http://www.csc.com/stealth3000 OPER_MOD,omitempty"`
	PRGINS  StrMxLn20  `xml:"http://www.csc.com/stealth3000 PRG_INS,omitempty"`
	PRGMOD  StrMxLn20  `xml:"http://www.csc.com/stealth3000 PRG_MOD,omitempty"`
	SOCINS  StrMxLn3   `xml:"http://www.csc.com/stealth3000 SOC_INS,omitempty"`
}

type TMessage struct {
	ORD       int       `xml:"http://www.csc.com/stealth3000 ORD,omitempty"`
	TYPE      StrMxLn1  `xml:"http://www.csc.com/stealth3000 TYPE,omitempty"`
	NUM       StrMxLn10 `xml:"http://www.csc.com/stealth3000 NUM,omitempty"`
	TEXT      string    `xml:"http://www.csc.com/stealth3000 TEXT,omitempty"`
	BLOCKCODE string    `xml:"http://www.csc.com/stealth3000 BLOCK_CODE,omitempty"`
	BLOCKDESC string    `xml:"http://www.csc.com/stealth3000 BLOCK_DESC,omitempty"`
	ITEMCODE  string    `xml:"http://www.csc.com/stealth3000 ITEM_CODE,omitempty"`
	ITEMDESC  string    `xml:"http://www.csc.com/stealth3000 ITEM_DESC,omitempty"`
	ITEMVALUE string    `xml:"http://www.csc.com/stealth3000 ITEM_VALUE,omitempty"`
}

// Notes
type TNOT struct {
	TPNCOD  StrMxLn2    `xml:"http://www.csc.com/stealth3000 TPN_COD"`
	LNGCOD  StrMxLn3    `xml:"http://www.csc.com/stealth3000 LNG_COD"`
	TESTO   StrMxLn4000 `xml:"http://www.csc.com/stealth3000 TESTO"`
	FANNU   StrFlag     `xml:"http://www.csc.com/stealth3000 F_ANNU"`
	DATAINS DateTime    `xml:"http://www.csc.com/stealth3000 DATA_INS,omitempty"`
	DATAMOD DateTime    `xml:"http://www.csc.com/stealth3000 DATA_MOD,omitempty"`
	OPERINS StrMxLn30   `xml:"http://www.csc.com/stealth3000 OPER_INS,omitempty"`
	OPERMOD StrMxLn30   `xml:"http://www.csc.com/stealth3000 OPER_MOD,omitempty"`
	PRGINS  StrMxLn20   `xml:"http://www.csc.com/stealth3000 PRG_INS,omitempty"`
	PRGMOD  StrMxLn20   `xml:"http://www.csc.com/stealth3000 PRG_MOD,omitempty"`
	SOCINS  StrMxLn3    `xml:"http://www.csc.com/stealth3000 SOC_INS,omitempty"`
}

type TResponseDA struct {
	ORIGAPPLICATIONAREA TApplicationArea `xml:"http://www.csc.com/stealth3000 ORIG_APPLICATIONAREA,omitempty"`
	ORIGDATAAREA        ORIGDATAAREA     `xml:"http://www.csc.com/stealth3000 ORIG_DATAAREA,omitempty"`
	IDDOCUMELAB         StrMxLn30        `xml:"http://www.csc.com/stealth3000 ID_DOCUM_ELAB,omitempty"`
	RETURN              TReturn          `xml:"http://www.csc.com/stealth3000 RETURN"`
	LISTMESSAGE         LISTMESSAGE      `xml:"http://www.csc.com/stealth3000 LIST_MESSAGE,omitempty"`
}

type TReturn struct {
	RETURNCODE int    `xml:"http://www.csc.com/stealth3000 RETURN_CODE"`
	TEXT       string `xml:"http://www.csc.com/stealth3000 TEXT,omitempty"`
}

type TSender struct {
	SISTEMA     StrMxLn30 `xml:"http://www.csc.com/stealth3000 SISTEMA,omitempty"`
	SOCIETA     StrMxLn3  `xml:"http://www.csc.com/stealth3000 SOCIETA,omitempty"`
	UTENTE      StrMxLn30 `xml:"http://www.csc.com/stealth3000 UTENTE,omitempty"`
	LINGUA      StrMxLn3  `xml:"http://www.csc.com/stealth3000 LINGUA,omitempty"`
	PROGRAMMA   StrMxLn30 `xml:"http://www.csc.com/stealth3000 PROGRAMMA,omitempty"`
	IDRICHIESTA StrMxLn20 `xml:"http://www.csc.com/stealth3000 ID_RICHIESTA,omitempty"`
	IDLANCIO    StrMxLn20 `xml:"http://www.csc.com/stealth3000 ID_LANCIO,omitempty"`
}

type TWHMovementSyncDel struct {
	APPLICATIONAREA TApplicationArea     `xml:"http://www.csc.com/stealth3000 APPLICATIONAREA"`
	DATAAREA        TWHMovementSyncDelDA `xml:"http://www.csc.com/stealth3000 DATAAREA"`
}

type TWHMovementSyncDelDA struct {
	PARAMETERS TWhMovementSyncDelPar `xml:"http://www.csc.com/stealth3000 PARAMETERS,omitempty"`
	WHMOVEMENT TBMGT                 `xml:"http://www.csc.com/stealth3000 WHMOVEMENT"`
}

type TWhMovementSyncDelPar struct {
	BOINBALANCE BOINBALANCE `xml:"http://www.csc.com/stealth3000 BOINBALANCE"`
}

type xsdDate time.Time

func (t *xsdDate) UnmarshalText(text []byte) error {
	return _unmarshalTime(text, (*time.Time)(t), "2006-01-02")
}
func (t xsdDate) MarshalText() ([]byte, error) {
	return _marshalTime((time.Time)(t), "2006-01-02")
}
func (t xsdDate) MarshalXML(e *xml.Encoder, start xml.StartElement) error {
	if (time.Time)(t).IsZero() {
		return nil
	}
	m, err := t.MarshalText()
	if err != nil {
		return err
	}
	return e.EncodeElement(m, start)
}
func (t xsdDate) MarshalXMLAttr(name xml.Name) (xml.Attr, error) {
	if (time.Time)(t).IsZero() {
		return xml.Attr{}, nil
	}
	m, err := t.MarshalText()
	return xml.Attr{Name: name, Value: string(m)}, err
}
func _unmarshalTime(text []byte, t *time.Time, format string) (err error) {
	s := string(bytes.TrimSpace(text))
	*t, err = time.Parse(format, s)
	if _, ok := err.(*time.ParseError); ok {
		*t, err = time.Parse(format+"Z07:00", s)
	}
	return err
}
func _marshalTime(t time.Time, format string) ([]byte, error) {
	return []byte(t.Format(format + "Z07:00")), nil
}

type xsdDateTime time.Time

func (t *xsdDateTime) UnmarshalText(text []byte) error {
	return _unmarshalTime(text, (*time.Time)(t), "2006-01-02T15:04:05.999999999")
}
func (t xsdDateTime) MarshalText() ([]byte, error) {
	return _marshalTime((time.Time)(t), "2006-01-02T15:04:05.999999999")
}
func (t xsdDateTime) MarshalXML(e *xml.Encoder, start xml.StartElement) error {
	if (time.Time)(t).IsZero() {
		return nil
	}
	m, err := t.MarshalText()
	if err != nil {
		return err
	}
	return e.EncodeElement(m, start)
}
func (t xsdDateTime) MarshalXMLAttr(name xml.Name) (xml.Attr, error) {
	if (time.Time)(t).IsZero() {
		return xml.Attr{}, nil
	}
	m, err := t.MarshalText()
	return xml.Attr{Name: name, Value: string(m)}, err
}
