package tables

import "importer/internal/iceberg"

// Code generated by gen_tables.go; DO NOT EDIT.

var MgtTable = iceberg.TableSchema{
	Name: "mgt",
	Fields: []iceberg.SchemaField{
		{Name: "bo_id", Type: "string", Required: true},
		{Name: "bo_partition_key", Type: "string", Required: true},
		{Name: "deleted", Type: "bool", Required: true},
		{Name: "last_update", Type: "timestamp", Required: true},
		{Name: "row_id", Type: "string", Required: true},
		{Name: "sandbox_package_guid", Type: "string", Required: true},
	},
	Partition:  []string{"bo_partition_key"},
	SortFields: []string{"bo_id"},
}

var MgtAssocTable = iceberg.TableSchema{
	Name: "mgt_assoc",
	Fields: []iceberg.SchemaField{
		{Name: "bo_id", Type: "string", Required: true},
		{Name: "bo_partition_key", Type: "string", Required: true},
		{Name: "deleted", Type: "bool", Required: true},
		{Name: "last_update", Type: "timestamp", Required: true},
		{Name: "main_mgt_anno", Type: "long", Required: false},
		{Name: "main_mgt_inm_cod", Type: "string", Required: false},
		{Name: "main_mgt_mga_cod", Type: "string", Required: false},
		{Name: "main_mgt_num", Type: "long", Required: false},
		{Name: "main_mgt_soc_cod", Type: "string", Required: false},
		{Name: "row_id", Type: "string", Required: true},
		{Name: "sandbox_package_guid", Type: "string", Required: true},
	},
	Partition:  []string{"bo_partition_key"},
	SortFields: []string{"bo_id"},
}

var MgtLniTable = iceberg.TableSchema{
	Name: "mgt_lni",
	Fields: []iceberg.SchemaField{
		{Name: "bo_id", Type: "string", Required: true},
		{Name: "bo_partition_key", Type: "string", Required: true},
		{Name: "deleted", Type: "bool", Required: true},
		{Name: "http://www.csc.com/stealth3000", Type: "string", Required: false},
		{Name: "last_update", Type: "timestamp", Required: true},
		{Name: "mgt_anno", Type: "long", Required: false},
		{Name: "mgt_inm_cod", Type: "string", Required: false},
		{Name: "mgt_mga_cod", Type: "string", Required: false},
		{Name: "mgt_num", Type: "long", Required: false},
		{Name: "mgt_soc_cod", Type: "string", Required: false},
		{Name: "row_id", Type: "string", Required: true},
		{Name: "sandbox_package_guid", Type: "string", Required: true},
	},
	Partition:  []string{"bo_partition_key"},
	SortFields: []string{"bo_id"},
}

var MgtMgrTable = iceberg.TableSchema{
	Name: "mgt_mgr",
	Fields: []iceberg.SchemaField{
		{Name: "bo_id", Type: "string", Required: true},
		{Name: "bo_partition_key", Type: "string", Required: true},
		{Name: "deleted", Type: "bool", Required: true},
		{Name: "last_update", Type: "timestamp", Required: true},
		{Name: "mgt_anno", Type: "long", Required: false},
		{Name: "mgt_inm_cod", Type: "string", Required: false},
		{Name: "mgt_mga_cod", Type: "string", Required: false},
		{Name: "mgt_num", Type: "long", Required: false},
		{Name: "mgt_soc_cod", Type: "string", Required: false},
		{Name: "row_id", Type: "string", Required: true},
		{Name: "sandbox_package_guid", Type: "string", Required: true},
	},
	Partition:  []string{"bo_partition_key"},
	SortFields: []string{"bo_id"},
}

var MgtMgrAgeTable = iceberg.TableSchema{
	Name: "mgt_mgr_age",
	Fields: []iceberg.SchemaField{
		{Name: "bo_id", Type: "string", Required: true},
		{Name: "bo_partition_key", Type: "string", Required: true},
		{Name: "deleted", Type: "bool", Required: true},
		{Name: "last_update", Type: "timestamp", Required: true},
		{Name: "mgr_riga", Type: "long", Required: false},
		{Name: "mgt_anno", Type: "long", Required: false},
		{Name: "mgt_inm_cod", Type: "string", Required: false},
		{Name: "mgt_mga_cod", Type: "string", Required: false},
		{Name: "mgt_num", Type: "long", Required: false},
		{Name: "mgt_soc_cod", Type: "string", Required: false},
		{Name: "row_id", Type: "string", Required: true},
		{Name: "sandbox_package_guid", Type: "string", Required: true},
	},
	Partition:  []string{"bo_partition_key"},
	SortFields: []string{"bo_id"},
}

var MgtMgrAgePrvTable = iceberg.TableSchema{
	Name: "mgt_mgr_age_prv",
	Fields: []iceberg.SchemaField{
		{Name: "bo_id", Type: "string", Required: true},
		{Name: "bo_partition_key", Type: "string", Required: true},
		{Name: "deleted", Type: "bool", Required: true},
		{Name: "last_update", Type: "timestamp", Required: true},
		{Name: "mgr_riga", Type: "long", Required: false},
		{Name: "mgt_anno", Type: "long", Required: false},
		{Name: "mgt_inm_cod", Type: "string", Required: false},
		{Name: "mgt_mga_cod", Type: "string", Required: false},
		{Name: "mgt_num", Type: "long", Required: false},
		{Name: "mgt_soc_cod", Type: "string", Required: false},
		{Name: "row_id", Type: "string", Required: true},
		{Name: "sandbox_package_guid", Type: "string", Required: true},
	},
	Partition:  []string{"bo_partition_key"},
	SortFields: []string{"bo_id"},
}

var MgtMgrAssocTable = iceberg.TableSchema{
	Name: "mgt_mgr_assoc",
	Fields: []iceberg.SchemaField{
		{Name: "bo_id", Type: "string", Required: true},
		{Name: "bo_partition_key", Type: "string", Required: true},
		{Name: "deleted", Type: "bool", Required: true},
		{Name: "last_update", Type: "timestamp", Required: true},
		{Name: "mgr_riga", Type: "long", Required: false},
		{Name: "mgt_anno", Type: "long", Required: false},
		{Name: "mgt_inm_cod", Type: "string", Required: false},
		{Name: "mgt_mga_cod", Type: "string", Required: false},
		{Name: "mgt_num", Type: "long", Required: false},
		{Name: "mgt_soc_cod", Type: "string", Required: false},
		{Name: "row_id", Type: "string", Required: true},
		{Name: "sandbox_package_guid", Type: "string", Required: true},
	},
	Partition:  []string{"bo_partition_key"},
	SortFields: []string{"bo_id"},
}

var MgtMgrAssocBarTable = iceberg.TableSchema{
	Name: "mgt_mgr_assoc_bar",
	Fields: []iceberg.SchemaField{
		{Name: "bo_id", Type: "string", Required: true},
		{Name: "bo_partition_key", Type: "string", Required: true},
		{Name: "deleted", Type: "bool", Required: true},
		{Name: "last_update", Type: "timestamp", Required: true},
		{Name: "main_mgr_riga", Type: "long", Required: false},
		{Name: "main_mgt_anno", Type: "long", Required: false},
		{Name: "main_mgt_inm_cod", Type: "string", Required: false},
		{Name: "main_mgt_mga_cod", Type: "string", Required: false},
		{Name: "main_mgt_num", Type: "long", Required: false},
		{Name: "main_mgt_soc_cod", Type: "string", Required: false},
		{Name: "mgr_riga", Type: "long", Required: false},
		{Name: "row_id", Type: "string", Required: true},
		{Name: "sandbox_package_guid", Type: "string", Required: true},
	},
	Partition:  []string{"bo_partition_key"},
	SortFields: []string{"bo_id"},
}

var MgtMgrAssocTglTable = iceberg.TableSchema{
	Name: "mgt_mgr_assoc_tgl",
	Fields: []iceberg.SchemaField{
		{Name: "bo_id", Type: "string", Required: true},
		{Name: "bo_partition_key", Type: "string", Required: true},
		{Name: "deleted", Type: "bool", Required: true},
		{Name: "last_update", Type: "timestamp", Required: true},
		{Name: "main_mgr_riga", Type: "long", Required: false},
		{Name: "main_mgt_anno", Type: "long", Required: false},
		{Name: "main_mgt_inm_cod", Type: "string", Required: false},
		{Name: "main_mgt_mga_cod", Type: "string", Required: false},
		{Name: "main_mgt_num", Type: "long", Required: false},
		{Name: "main_mgt_soc_cod", Type: "string", Required: false},
		{Name: "mgr_riga", Type: "long", Required: false},
		{Name: "row_id", Type: "string", Required: true},
		{Name: "sandbox_package_guid", Type: "string", Required: true},
	},
	Partition:  []string{"bo_partition_key"},
	SortFields: []string{"bo_id"},
}

var MgtMgrAssocValTable = iceberg.TableSchema{
	Name: "mgt_mgr_assoc_val",
	Fields: []iceberg.SchemaField{
		{Name: "bo_id", Type: "string", Required: true},
		{Name: "bo_partition_key", Type: "string", Required: true},
		{Name: "deleted", Type: "bool", Required: true},
		{Name: "last_update", Type: "timestamp", Required: true},
		{Name: "main_mgr_riga", Type: "long", Required: false},
		{Name: "main_mgt_anno", Type: "long", Required: false},
		{Name: "main_mgt_inm_cod", Type: "string", Required: false},
		{Name: "main_mgt_mga_cod", Type: "string", Required: false},
		{Name: "main_mgt_num", Type: "long", Required: false},
		{Name: "main_mgt_soc_cod", Type: "string", Required: false},
		{Name: "mgr_riga", Type: "long", Required: false},
		{Name: "row_id", Type: "string", Required: true},
		{Name: "sandbox_package_guid", Type: "string", Required: true},
	},
	Partition:  []string{"bo_partition_key"},
	SortFields: []string{"bo_id"},
}

var MgtMgrBarTable = iceberg.TableSchema{
	Name: "mgt_mgr_bar",
	Fields: []iceberg.SchemaField{
		{Name: "bo_id", Type: "string", Required: true},
		{Name: "bo_partition_key", Type: "string", Required: true},
		{Name: "deleted", Type: "bool", Required: true},
		{Name: "last_update", Type: "timestamp", Required: true},
		{Name: "mgr_riga", Type: "long", Required: false},
		{Name: "mgt_anno", Type: "long", Required: false},
		{Name: "mgt_inm_cod", Type: "string", Required: false},
		{Name: "mgt_mga_cod", Type: "string", Required: false},
		{Name: "mgt_num", Type: "long", Required: false},
		{Name: "mgt_soc_cod", Type: "string", Required: false},
		{Name: "row_id", Type: "string", Required: true},
		{Name: "sandbox_package_guid", Type: "string", Required: true},
	},
	Partition:  []string{"bo_partition_key"},
	SortFields: []string{"bo_id"},
}

var MgtMgrCdsTable = iceberg.TableSchema{
	Name: "mgt_mgr_cds",
	Fields: []iceberg.SchemaField{
		{Name: "bo_id", Type: "string", Required: true},
		{Name: "bo_partition_key", Type: "string", Required: true},
		{Name: "deleted", Type: "bool", Required: true},
		{Name: "last_update", Type: "timestamp", Required: true},
		{Name: "mgr_riga", Type: "long", Required: false},
		{Name: "mgt_anno", Type: "long", Required: false},
		{Name: "mgt_inm_cod", Type: "string", Required: false},
		{Name: "mgt_mga_cod", Type: "string", Required: false},
		{Name: "mgt_num", Type: "long", Required: false},
		{Name: "mgt_soc_cod", Type: "string", Required: false},
		{Name: "row_id", Type: "string", Required: true},
		{Name: "sandbox_package_guid", Type: "string", Required: true},
	},
	Partition:  []string{"bo_partition_key"},
	SortFields: []string{"bo_id"},
}

var MgtMgrCdsCprTglTable = iceberg.TableSchema{
	Name: "mgt_mgr_cds_cpr_tgl",
	Fields: []iceberg.SchemaField{
		{Name: "bo_id", Type: "string", Required: true},
		{Name: "bo_partition_key", Type: "string", Required: true},
		{Name: "deleted", Type: "bool", Required: true},
		{Name: "last_update", Type: "timestamp", Required: true},
		{Name: "mgr_riga", Type: "long", Required: false},
		{Name: "mgt_anno", Type: "long", Required: false},
		{Name: "mgt_inm_cod", Type: "string", Required: false},
		{Name: "mgt_mga_cod", Type: "string", Required: false},
		{Name: "mgt_num", Type: "long", Required: false},
		{Name: "mgt_soc_cod", Type: "string", Required: false},
		{Name: "row_id", Type: "string", Required: true},
		{Name: "sandbox_package_guid", Type: "string", Required: true},
	},
	Partition:  []string{"bo_partition_key"},
	SortFields: []string{"bo_id"},
}

var MgtMgrGrtFprTable = iceberg.TableSchema{
	Name: "mgt_mgr_grt_fpr",
	Fields: []iceberg.SchemaField{
		{Name: "bo_id", Type: "string", Required: true},
		{Name: "bo_partition_key", Type: "string", Required: true},
		{Name: "deleted", Type: "bool", Required: true},
		{Name: "last_update", Type: "timestamp", Required: true},
		{Name: "mgr_riga", Type: "long", Required: false},
		{Name: "mgt_anno", Type: "long", Required: false},
		{Name: "mgt_inm_cod", Type: "string", Required: false},
		{Name: "mgt_mga_cod", Type: "string", Required: false},
		{Name: "mgt_num", Type: "long", Required: false},
		{Name: "mgt_soc_cod", Type: "string", Required: false},
		{Name: "row_id", Type: "string", Required: true},
		{Name: "sandbox_package_guid", Type: "string", Required: true},
	},
	Partition:  []string{"bo_partition_key"},
	SortFields: []string{"bo_id"},
}

var MgtMgrMgcTable = iceberg.TableSchema{
	Name: "mgt_mgr_mgc",
	Fields: []iceberg.SchemaField{
		{Name: "bo_id", Type: "string", Required: true},
		{Name: "bo_partition_key", Type: "string", Required: true},
		{Name: "deleted", Type: "bool", Required: true},
		{Name: "last_update", Type: "timestamp", Required: true},
		{Name: "mgr_riga", Type: "long", Required: false},
		{Name: "mgt_anno", Type: "long", Required: false},
		{Name: "mgt_inm_cod", Type: "string", Required: false},
		{Name: "mgt_mga_cod", Type: "string", Required: false},
		{Name: "mgt_num", Type: "long", Required: false},
		{Name: "mgt_soc_cod", Type: "string", Required: false},
		{Name: "row_id", Type: "string", Required: true},
		{Name: "sandbox_package_guid", Type: "string", Required: true},
	},
	Partition:  []string{"bo_partition_key"},
	SortFields: []string{"bo_id"},
}

var MgtMgrMgpTable = iceberg.TableSchema{
	Name: "mgt_mgr_mgp",
	Fields: []iceberg.SchemaField{
		{Name: "bo_id", Type: "string", Required: true},
		{Name: "bo_partition_key", Type: "string", Required: true},
		{Name: "deleted", Type: "bool", Required: true},
		{Name: "last_update", Type: "timestamp", Required: true},
		{Name: "mgr_riga", Type: "long", Required: false},
		{Name: "mgt_anno", Type: "long", Required: false},
		{Name: "mgt_inm_cod", Type: "string", Required: false},
		{Name: "mgt_mga_cod", Type: "string", Required: false},
		{Name: "mgt_num", Type: "long", Required: false},
		{Name: "mgt_soc_cod", Type: "string", Required: false},
		{Name: "row_id", Type: "string", Required: true},
		{Name: "sandbox_package_guid", Type: "string", Required: true},
	},
	Partition:  []string{"bo_partition_key"},
	SortFields: []string{"bo_id"},
}

var MgtMgrNotTable = iceberg.TableSchema{
	Name: "mgt_mgr_not",
	Fields: []iceberg.SchemaField{
		{Name: "bo_id", Type: "string", Required: true},
		{Name: "bo_partition_key", Type: "string", Required: true},
		{Name: "deleted", Type: "bool", Required: true},
		{Name: "http://www.csc.com/stealth3000", Type: "string", Required: false},
		{Name: "last_update", Type: "timestamp", Required: true},
		{Name: "mgr_riga", Type: "long", Required: false},
		{Name: "mgt_anno", Type: "long", Required: false},
		{Name: "mgt_inm_cod", Type: "string", Required: false},
		{Name: "mgt_mga_cod", Type: "string", Required: false},
		{Name: "mgt_num", Type: "long", Required: false},
		{Name: "mgt_soc_cod", Type: "string", Required: false},
		{Name: "row_id", Type: "string", Required: true},
		{Name: "sandbox_package_guid", Type: "string", Required: true},
	},
	Partition:  []string{"bo_partition_key"},
	SortFields: []string{"bo_id"},
}

var MgtMgrTglTable = iceberg.TableSchema{
	Name: "mgt_mgr_tgl",
	Fields: []iceberg.SchemaField{
		{Name: "bo_id", Type: "string", Required: true},
		{Name: "bo_partition_key", Type: "string", Required: true},
		{Name: "deleted", Type: "bool", Required: true},
		{Name: "last_update", Type: "timestamp", Required: true},
		{Name: "mgr_riga", Type: "long", Required: false},
		{Name: "mgt_anno", Type: "long", Required: false},
		{Name: "mgt_inm_cod", Type: "string", Required: false},
		{Name: "mgt_mga_cod", Type: "string", Required: false},
		{Name: "mgt_num", Type: "long", Required: false},
		{Name: "mgt_soc_cod", Type: "string", Required: false},
		{Name: "row_id", Type: "string", Required: true},
		{Name: "sandbox_package_guid", Type: "string", Required: true},
	},
	Partition:  []string{"bo_partition_key"},
	SortFields: []string{"bo_id"},
}

var MgtNotTable = iceberg.TableSchema{
	Name: "mgt_not",
	Fields: []iceberg.SchemaField{
		{Name: "bo_id", Type: "string", Required: true},
		{Name: "bo_partition_key", Type: "string", Required: true},
		{Name: "deleted", Type: "bool", Required: true},
		{Name: "http://www.csc.com/stealth3000", Type: "string", Required: false},
		{Name: "last_update", Type: "timestamp", Required: true},
		{Name: "mgt_anno", Type: "long", Required: false},
		{Name: "mgt_inm_cod", Type: "string", Required: false},
		{Name: "mgt_mga_cod", Type: "string", Required: false},
		{Name: "mgt_num", Type: "long", Required: false},
		{Name: "mgt_soc_cod", Type: "string", Required: false},
		{Name: "row_id", Type: "string", Required: true},
		{Name: "sandbox_package_guid", Type: "string", Required: true},
	},
	Partition:  []string{"bo_partition_key"},
	SortFields: []string{"bo_id"},
}

var MgtSpeTable = iceberg.TableSchema{
	Name: "mgt_spe",
	Fields: []iceberg.SchemaField{
		{Name: "bo_id", Type: "string", Required: true},
		{Name: "bo_partition_key", Type: "string", Required: true},
		{Name: "deleted", Type: "bool", Required: true},
		{Name: "http://www.csc.com/stealth3000", Type: "string", Required: false},
		{Name: "last_update", Type: "timestamp", Required: true},
		{Name: "mgt_anno", Type: "long", Required: false},
		{Name: "mgt_inm_cod", Type: "string", Required: false},
		{Name: "mgt_mga_cod", Type: "string", Required: false},
		{Name: "mgt_num", Type: "long", Required: false},
		{Name: "mgt_soc_cod", Type: "string", Required: false},
		{Name: "row_id", Type: "string", Required: true},
		{Name: "sandbox_package_guid", Type: "string", Required: true},
	},
	Partition:  []string{"bo_partition_key"},
	SortFields: []string{"bo_id"},
}
